import { BarChart3, Building2, ClipboardList, Compass, FileCheck2, Map, MapPinned, ScanLine, ShieldCheck, TrendingUp } from "lucide-react";
import { useMemo, useState } from "react";

const layers = [
  { name: "Approved facility boundary", steward: "Facilities Security", version: "v3.2", quality: "Verified", coverage: 92 },
  { name: "Floor-plan review baseline", steward: "Site Operations", version: "v1.4", quality: "Reviewed", coverage: 76 },
  { name: "Imagery review plan", steward: "Assessment Lead", version: "v0.8", quality: "Planned", coverage: 44 },
  { name: "Field coordination zones", steward: "Engagement Manager", version: "v2.0", quality: "Verified", coverage: 88 },
];
const scenarios = [
  { name: "Edge remediation first", reduction: 34, effort: 18, service: "Gateway telemetry" },
  { name: "Identity hardening first", reduction: 28, effort: 14, service: "Control plane" },
  { name: "Provider dependency review", reduction: 19, effort: 9, service: "Regional reporting" },
];
const controls = [
  ["Authorization & scope", "Scope document, exclusions, expiration, and reviewer approval"],
  ["Evidence lifecycle", "Custody, classification, retention, legal hold, and deletion review"],
  ["Spatial privacy", "Layer minimization, coordinate precision, facility stewardship, and export redaction"],
  ["Delivery assurance", "Audience, exception, attestation, expiry, and closure evidence"],
] as const;

export default function AdvancedSpatialRiskAssuranceLab() {
  const [selectedScenario, setSelectedScenario] = useState(0);
  const [controlComplete, setControlComplete] = useState<Record<string, boolean>>({});
  const selected = scenarios[selectedScenario];
  const averageCoverage = useMemo(() => Math.round(layers.reduce((sum, layer) => sum + layer.coverage, 0) / layers.length), []);
  return <section className="mt-4 atlas-surface p-4"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-start"><div><p className="eyebrow">ADVANCED GIS, RISK INTELLIGENCE & ASSURANCE</p><h3 className="mt-1 font-['Barlow_Condensed'] text-2xl font-semibold tracking-[.07em] text-white">SPATIAL DECISION & CONTROL LAB</h3><p className="mt-1 max-w-3xl text-xs leading-5 text-white/52">Plan authorized GIS coverage, field coordination, impact-aware remediation, scenario comparison, executive trends, and assurance evidence from fictional records. Values are illustrative and must not be treated as forecasts or operational instructions.</p></div><span className="atlas-status">Synthetic decision support</span></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.15fr_.85fr]"><section className="rounded-lg border border-white/8 bg-black/20 p-3"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><Map size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/76">Spatial data stewardship & coverage</p></div><span className="text-[10px] text-[#f2cb82]">{averageCoverage}% aggregate review coverage</span></div><div className="mt-3 grid gap-2">{layers.map((layer) => <div key={layer.name} className="rounded border border-white/8 p-2.5"><div className="flex justify-between gap-3 text-[10px]"><span className="text-white/70">{layer.name}</span><span className="text-[#b9c7ff]">{layer.version} · {layer.quality}</span></div><p className="mt-1 text-[9px] text-white/42">Steward: {layer.steward}</p><div className="mt-2 h-1.5 overflow-hidden rounded bg-white/8"><div className="h-full rounded bg-gradient-to-r from-[#60401c] to-[#e8b760]" style={{ width: `${layer.coverage}%` }}/></div></div>)}</div><div className="mt-3 grid grid-cols-3 gap-2 text-center text-[9px]"><span className="rounded border border-white/8 p-2 text-white/48"><MapPinned size={13} className="mx-auto mb-1 text-[#b9c7ff]"/>Field safety card</span><span className="rounded border border-white/8 p-2 text-white/48"><Building2 size={13} className="mx-auto mb-1 text-[#b9c7ff]"/>Plan version review</span><span className="rounded border border-white/8 p-2 text-white/48"><ScanLine size={13} className="mx-auto mb-1 text-[#b9c7ff]"/>Imagery review plan</span></div></section>
      <section className="rounded-lg border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><TrendingUp size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/76">Executive trend & portfolio context</p></div><div className="mt-3 grid grid-cols-2 gap-2">{[["Service blast radius", "3 dependent services"],["Provider concentration", "2 critical paths"],["Control-gap heat", "2 priority zones"],["Risk trend", "−12% planned" ]].map(([label, value]) => <div key={label} className="rounded border border-white/8 p-2.5"><p className="text-[9px] uppercase tracking-[.12em] text-white/35">{label}</p><p className="mt-1 text-[11px] text-white/73">{value}</p></div>)}</div><div className="mt-3 rounded border border-[#e8b760]/18 bg-[#e8b760]/[.045] p-3 text-[10px] leading-4 text-white/55">Trend uses synthetic planning assumptions only. A private deployment should surface data age, confidence, methodology, and decision owner beside any business-impact view.</div></section></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1fr_1fr]"><section className="rounded-lg border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><BarChart3 size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/76">Remediation scenario comparator</p></div><div className="mt-3 grid gap-2">{scenarios.map((scenario, index) => <button key={scenario.name} onClick={() => setSelectedScenario(index)} className={`rounded border p-2.5 text-left ${selectedScenario === index ? "border-[#e8b760]/35 bg-[#e8b760]/[.06]" : "border-white/8"}`}><div className="flex justify-between gap-2 text-[10px]"><span className="text-white/72">{scenario.name}</span><span className="text-[#f2cb82]">Synthetic reduction {scenario.reduction}%</span></div><p className="mt-1 text-[9px] text-white/42">Effort index {scenario.effort} · primary service: {scenario.service}</p></button>)}</div><p className="mt-3 rounded border border-white/8 p-2 text-[10px] text-white/53">Selected planning view: <b className="text-white/76">{selected.name}</b>. This prioritization aid does not prescribe remediation or estimate actual impact.</p></section>
      <section className="rounded-lg border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><ClipboardList size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/76">Assurance control library</p></div><div className="mt-3 grid gap-2">{controls.map(([title, detail]) => <label key={title} className={`flex gap-3 rounded border p-2.5 ${controlComplete[title] ? "border-[#83a77c]/30 bg-[#83a77c]/[.05]" : "border-white/8"}`}><input type="checkbox" checked={Boolean(controlComplete[title])} onChange={(event) => setControlComplete((current) => ({ ...current, [title]: event.target.checked }))} className="mt-0.5 accent-[#e8b760]"/><span><span className="block text-[10px] font-medium text-white/72">{title}</span><span className="mt-1 block text-[9px] leading-4 text-white/43">{detail}</span></span></label>)}</div><p className="mt-3 flex items-center gap-2 text-[10px] text-white/42"><FileCheck2 size={13} className="text-[#b9c7ff]"/>A private audit pack should link each completed control to the owner, evidence reference, review date, exception, and attestation.</p></section></div>
    <p className="mt-4 flex items-center gap-2 text-[10px] text-white/42"><Compass size={13} className="text-[#e8b760]"/><ShieldCheck size={13} className="text-[#e8b760]"/>Spatial and risk decisions should remain authorization-bound, evidence-backed, privacy-aware, and analyst-approved.</p>
  </section>;
}
