import { trpc } from "@/lib/trpc";
import { Bot, CircleCheck, Sparkles, X } from "lucide-react";
import { useMemo } from "react";

export default function AnalystAssistant({ confirmed, onConfirm, onClose }: { confirmed: boolean; onConfirm: () => void; onClose: () => void }) {
  const assistantInput = useMemo(() => ({ findingId: "F-104", assetName: "edge.helix-labs.example", evidenceReference: "EV-309 · HTTP response and scope comparison", score: 100 }), []);
  const { data, isError, isLoading } = trpc.workspace.citedAssistantDraft.useQuery(assistantInput);
  const duplicateCitation = data?.citations.find((citation) => citation.relation === "Duplicate review context");
  return <aside className="fixed bottom-5 right-5 z-20 hidden w-[345px] overflow-hidden rounded-2xl border border-[#e8b760]/25 bg-[#0c0a07]/95 shadow-[0_28px_90px_rgba(0,0,0,.65)] backdrop-blur-xl 2xl:block"><div className="flex items-center justify-between border-b border-white/10 bg-[linear-gradient(110deg,rgba(232,183,96,.14),transparent)] px-4 py-3"><div className="flex items-center gap-2"><div className="flex h-7 w-7 items-center justify-center rounded-md bg-[#e8b760]/15 text-[#e8b760]"><Bot size={15}/></div><div><p className="text-xs font-semibold text-white">Analyst-confirmed assistant</p><p className="text-[10px] text-white/38">Citations required · no automatic changes</p></div></div><button onClick={onClose} className="text-white/40 hover:text-white" aria-label="Close analyst assistant"><X size={15}/></button></div><div className="p-4">{isError ? <p role="alert" className="text-xs leading-5 text-[#ffab9d]">The citation service is unavailable. No draft has been generated.</p> : <p className="text-xs leading-5 text-white/70">{isLoading ? "Preparing a citation-backed synthetic evidence summary." : data?.draft}</p>}<div className="mt-3 rounded-lg border border-white/10 bg-black/25 p-3"><p className="eyebrow">SUPPORTING WORKSPACE DATA</p><div className="mt-2 space-y-1.5 text-[11px] text-[#e6cb9a]">{data?.citations.map((citation) => <p key={citation.id}>[{citation.id}] {citation.label}</p>) ?? <p>Loading workspace citations…</p>}</div></div>{duplicateCitation && <div className="mt-3 rounded-lg border border-[#ef796a]/25 bg-[#ef796a]/[.055] p-3"><p className="eyebrow">LIKELY DUPLICATE / REVIEW REQUIRED</p><p className="mt-2 text-[11px] leading-5 text-white/60">The assistant flags a synthetic case-variant duplicate candidate based on [{duplicateCitation.id}] {duplicateCitation.label}. It will not merge or suppress either record.</p></div>}<div className="mt-3 rounded-lg border border-[#e8b760]/20 bg-[#e8b760]/[.055] p-3"><p className="eyebrow">CONTROL BOUNDARY</p><p className="mt-2 text-[11px] leading-5 text-white/60">This output is a draft. It cannot update a finding, report, or scope boundary unless an analyst confirms it.</p></div><button onClick={onConfirm} disabled={isError || isLoading} className={`mt-4 flex w-full items-center justify-center gap-2 rounded-lg px-3 py-2.5 text-xs font-semibold transition-colors ${confirmed ? "bg-[#83a77c]/20 text-[#bde0b5]" : "bg-[#e8b760] text-[#1c1306] hover:bg-[#f3cc80]"} disabled:cursor-not-allowed disabled:opacity-50`}>{confirmed ? <><CircleCheck size={15}/> Draft confirmed by analyst</> : <><Sparkles size={15}/> Confirm draft before use</>}</button></div></aside>;
}
