import { Activity, BadgeCheck, CircleDashed, Compass, GitBranch, MapPinned, ShieldAlert, Target } from "lucide-react";

const validationQueue = [
  { asset: "edge.helix-labs.example", service: "External partner gateway", owner: "Platform Engineering", criticality: "Critical", freshness: "12m", state: "Evidence review" },
  { asset: "203.0.113.18", service: "Telemetry relay", owner: "Infrastructure", criticality: "High", freshness: "18m", state: "Scope verified" },
  { asset: "api.helix-labs.example", service: "Customer API control plane", owner: "Application Security", criticality: "High", freshness: "22m", state: "Retest queued" },
  { asset: "Aurora Compute Region", service: "Regional compute dependency", owner: "Cloud Engineering", criticality: "Medium", freshness: "41m", state: "Context review" },
];

const hypotheses = [
  { path: "Internet edge → partner gateway → telemetry relay", confidence: "Evidence-backed", status: "Validate control ownership", tone: "gold" },
  { path: "Cloud identity boundary → regional compute dependency → API control plane", confidence: "Analyst hypothesis", status: "Needs approved evidence", tone: "blue" },
  { path: "Site access transition → operations zone → protected service context", confidence: "Planning context", status: "Requires site authorization", tone: "green" },
];

const coverageGaps = [
  { domain: "Asset ownership", coverage: 92, detail: "One provider dependency lacks accountable owner confirmation" },
  { domain: "Evidence freshness", coverage: 74, detail: "Two synthetic observations are outside the preferred 30-minute review window" },
  { domain: "Cloud context", coverage: 68, detail: "Identity and business-service linkage await private connector approval" },
  { domain: "Physical / GIS scope", coverage: 86, detail: "Northstar access-route review is prepared; no live facility data is loaded" },
];

export default function AuthorizedAssessmentWorkbench() {
  return <section className="mt-4 atlas-surface p-4"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-start"><div><p className="eyebrow">AUTHORIZED ASSESSMENT INTELLIGENCE</p><h3 className="mt-1 font-['Barlow_Condensed'] text-2xl font-semibold tracking-[.07em] text-white">ATTACK-SURFACE DECISION WORKBENCH</h3><p className="mt-1 max-w-3xl text-xs leading-5 text-white/52">A controlled planning layer for validating synthetic asset context, evidence freshness, service ownership, exposure-path hypotheses, assessment coverage, and field/remote coordination. It models decisions; it does not scan, exploit, or target systems.</p></div><span className="atlas-status">Analyst confirmation required</span></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.12fr_.88fr]"><section className="rounded-lg border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><Target size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/78">Evidence validation queue</p></div><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-[10px]"><thead className="border-b border-white/8 text-[9px] uppercase tracking-[.12em] text-white/35"><tr><th className="pb-2 font-medium">Asset / service</th><th className="pb-2 font-medium">Owner</th><th className="pb-2 font-medium">Criticality</th><th className="pb-2 font-medium">Freshness</th><th className="pb-2 font-medium">Validation</th></tr></thead><tbody>{validationQueue.map((item) => <tr key={item.asset} className="border-b border-white/[.055]"><td className="py-2.5"><p className="font-medium text-white/75">{item.asset}</p><p className="mt-0.5 text-white/38">{item.service}</p></td><td className="py-2.5 text-white/55">{item.owner}</td><td className="py-2.5 text-[#f2cb82]">{item.criticality}</td><td className="py-2.5 text-[#b9c7ff]">{item.freshness}</td><td className="py-2.5"><span className="rounded border border-white/10 px-1.5 py-1 text-white/55">{item.state}</span></td></tr>)}</tbody></table></div><p className="mt-3 text-[10px] text-white/42">Private deployments may enrich this queue with consented CMDB, cloud, EDR, vulnerability, ticketing, and ownership data after the readiness gates are satisfied.</p></section>
      <section className="rounded-lg border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><GitBranch size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/78">Exposure-path hypotheses</p></div><div className="mt-3 grid gap-2">{hypotheses.map((item) => <div key={item.path} className="rounded border border-white/8 bg-black/20 p-2.5"><p className="text-[11px] leading-5 text-white/72">{item.path}</p><div className="mt-2 flex items-center justify-between gap-2"><span className={`text-[9px] ${item.tone === "gold" ? "text-[#f2cb82]" : item.tone === "blue" ? "text-[#b9c7ff]" : "text-[#bde0b5]"}`}>{item.confidence}</span><span className="text-[9px] text-white/40">{item.status}</span></div></div>)}</div></section></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1fr_.9fr]"><section className="rounded-lg border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><CircleDashed size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/78">Assessment coverage gaps</p></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{coverageGaps.map((item) => <div key={item.domain} className="rounded border border-white/8 p-2.5"><div className="flex justify-between text-[10px]"><span className="text-white/60">{item.domain}</span><span className="text-[#f2cb82]">{item.coverage}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded bg-white/8"><div className="h-full rounded bg-gradient-to-r from-[#81531d] to-[#e8b760]" style={{ width: `${item.coverage}%` }}/></div><p className="mt-2 text-[10px] leading-4 text-white/42">{item.detail}</p></div>)}</div></section>
      <section className="rounded-lg border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><MapPinned size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/78">GIS coordination zones</p></div><div className="mt-3 grid gap-2">{[["Northstar relay campus","Access-route review · floor-plan work zone","Synthetic local planning"],["Aurora compute region","Cloud dependency review · identity context","Synthetic regional context"],["Solstice transit context","Provider relationship review · evidence freshness","Synthetic inferred context"]].map(([name, workflow, type]) => <div key={name} className="flex items-start gap-3 rounded border border-white/8 p-2.5"><Compass size={14} className="mt-0.5 text-[#b9c7ff]"/><div><p className="text-[11px] text-white/72">{name}</p><p className="mt-1 text-[10px] text-white/45">{workflow}</p><p className="mt-1 text-[9px] uppercase tracking-[.1em] text-[#b9c7ff]">{type}</p></div></div>)}</div></section></div>
    <div className="mt-4 flex items-center gap-2 rounded border border-[#e8b760]/18 bg-[#e8b760]/[.045] px-3 py-2 text-[10px] text-white/55"><Activity size={13} className="text-[#f2cb82]"/>No exposure path is treated as confirmed, and no asset action is performed, without evidence and analyst confirmation inside an explicitly authorized engagement.</div>
  </section>;
}
