import { BadgeCheck, Boxes, Braces, CircleDotDashed, GitCompareArrows, Network, ShieldCheck } from "lucide-react";
import { useState } from "react";

type Tab = "campaign" | "graph" | "policy";
const campaigns = [["External surface", "Approved scope", "4/6 milestones", "2 analysts"],["Cloud posture", "Review gate", "2/5 milestones", "1 analyst"],["Facilities assurance", "Field plan", "3/4 milestones", "2 reviewers"],["Executive exercise", "Sponsor approval", "1/3 milestones", "1 manager"]] as const;
const deltas = [["Service owner changed", "Helix gateway", "Review handoff"],["Evidence freshness threshold", "Northstar relay", "Refresh required"],["Provider relation inferred", "Solstice transit", "Confirm provenance"],["Scope window nearing expiry", "Campaign ENG-2026-08", "Approval gate"]] as const;

export default function CampaignGraphPolicyStudio() {
  const [tab, setTab] = useState<Tab>("campaign"); const [policy, setPolicy] = useState("require approval before client delivery and external adapter activation");
  return <section className="mt-4 atlas-surface p-4"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-start"><div><p className="eyebrow">CAMPAIGN, KNOWLEDGE GRAPH & POLICY STUDIO</p><h3 className="mt-1 font-['Barlow_Condensed'] text-2xl font-semibold tracking-[.07em] text-white">ASSESSMENT PROGRAM CONTROL</h3><p className="mt-1 max-w-3xl text-xs leading-5 text-white/52">Coordinate synthetic assessment campaigns, explain relationships, stage change review, and dry-run governed policy logic. Nothing here scans, acts on, or connects to real systems.</p></div><span className="atlas-status">Synthetic planning only</span></div>
    <div className="mt-4 flex gap-1 border-b border-white/8 pb-2">{(["campaign","graph","policy"] as Tab[]).map((item)=><button key={item} onClick={()=>setTab(item)} className={`rounded px-3 py-1.5 text-[10px] uppercase tracking-[.13em] ${tab===item?"bg-[#e8b760]/12 text-[#f2cb82]":"text-white/46"}`}>{item}</button>)}</div>
    {tab==="campaign" && <div className="mt-4 grid gap-3 xl:grid-cols-2">{campaigns.map(([name,gate,milestone,staff])=><div key={name} className="rounded-lg border border-white/8 bg-black/20 p-3"><div className="flex justify-between gap-2"><p className="text-xs font-semibold text-white/76">{name}</p><span className="text-[10px] text-[#f2cb82]">{gate}</span></div><div className="mt-3 grid grid-cols-3 gap-2 text-center text-[9px]"><span className="rounded border border-white/8 p-2 text-white/55">{milestone}</span><span className="rounded border border-white/8 p-2 text-white/55">{staff}</span><span className="rounded border border-white/8 p-2 text-white/55">Budget: synthetic</span></div><p className="mt-3 text-[10px] text-white/43">Dependencies: authorization → scope → evidence → review → delivery → closure certification.</p></div>)}</div>}
    {tab==="graph" && <div className="mt-4 grid gap-4 xl:grid-cols-[1fr_.9fr]"><div className="rounded-lg border border-white/8 bg-black/20 p-4"><div className="relative h-52 overflow-hidden rounded border border-white/8 bg-[radial-gradient(circle_at_50%_50%,rgba(232,183,96,.14),transparent_55%)]"><span className="absolute left-[8%] top-[45%] rounded border border-[#e8b760]/30 px-2 py-1 text-[10px] text-[#f2cb82]">Asset</span><span className="absolute left-[34%] top-[18%] rounded border border-[#b9c7ff]/30 px-2 py-1 text-[10px] text-[#b9c7ff]">Service</span><span className="absolute left-[54%] top-[48%] rounded border border-[#83a77c]/30 px-2 py-1 text-[10px] text-[#bde0b5]">Control</span><span className="absolute right-[8%] top-[20%] rounded border border-[#ee7664]/30 px-2 py-1 text-[10px] text-[#ffab9d]">Finding</span><span className="absolute right-[13%] bottom-[14%] rounded border border-white/20 px-2 py-1 text-[10px] text-white/62">Evidence</span><div className="absolute left-[18%] top-[52%] h-px w-[22%] rotate-[-25deg] bg-[#e8b760]/40"/><div className="absolute left-[48%] top-[46%] h-px w-[18%] rotate-[15deg] bg-[#b9c7ff]/40"/><div className="absolute left-[63%] top-[35%] h-px w-[20%] rotate-[-18deg] bg-[#ee7664]/40"/></div><p className="mt-3 flex items-center gap-2 text-[10px] text-white/44"><Network size={13} className="text-[#e8b760]"/>Graph links assets, identities, services, data classes, providers, controls, evidence, findings, and owners in a private tenant.</p></div><div className="rounded-lg border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><GitCompareArrows size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/76">Change-intelligence queue</p></div><div className="mt-3 grid gap-2">{deltas.map(([change,object,action])=><div key={change} className="rounded border border-white/8 p-2 text-[10px]"><div className="flex justify-between gap-2"><span className="text-white/68">{change}</span><span className="text-[#f2cb82]">{action}</span></div><p className="mt-1 text-white/42">{object} · synthetic delta</p></div>)}</div></div></div>}
    {tab==="policy" && <div className="mt-4 grid gap-4 xl:grid-cols-[1fr_.9fr]"><div className="rounded-lg border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><Braces size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/76">Policy-as-code dry run</p></div><textarea value={policy} onChange={(e)=>setPolicy(e.target.value)} className="mt-3 min-h-28 w-full rounded border border-white/10 bg-black/25 p-2 text-xs text-white"/><p className="mt-2 text-[10px] text-white/42">Private implementations should parse signed policy bundles, enforce decision points server-side, version rules, and emit auditable outcomes.</p></div><div className="rounded-lg border border-[#e8b760]/18 bg-[#e8b760]/[.045] p-3"><div className="flex items-center gap-2"><ShieldCheck size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/76">Synthetic policy result</p></div><div className="mt-3 grid gap-2 text-[10px] text-white/58"><p className="rounded border border-white/8 p-2">Scope gate: <b className="text-[#bde0b5]">pass</b></p><p className="rounded border border-white/8 p-2">Redaction profile: <b className="text-[#bde0b5]">required</b></p><p className="rounded border border-white/8 p-2">Delivery approval: <b className="text-[#f2cb82]">reviewer required</b></p><p className="rounded border border-white/8 p-2">Connector activation: <b className="text-[#ffab9d]">blocked in public build</b></p></div><p className="mt-3 flex gap-2 text-[10px] text-white/42"><BadgeCheck size={13} className="text-[#b9c7ff]"/>Control mapping can attach each policy result to control owner, framework gap, evidence request, exception, and attestation.</p></div></div>}
  </section>;
}
