import { BriefcaseBusiness, CheckCircle2, ChevronRight, Cloud, Crosshair, Map, RadioTower, Smartphone, Wifi, Workflow } from "lucide-react";
import { useState } from "react";

const campaigns = [
  { id: "external", label: "External surface", icon: Crosshair, objective: "Validate organization-approved external asset coverage and exposure evidence.", gates: ["Scope certificate", "Asset owner", "Evidence intake"], work: "DNS / provider / service relationships" },
  { id: "internal", label: "Internal assessment", icon: Workflow, objective: "Plan scoped identity, segmentation, service-ownership, and remediation validation.", gates: ["Network boundary", "Identity boundary", "Change window"], work: "Business-service and control-path review" },
  { id: "cloud", label: "Cloud posture", icon: Cloud, objective: "Map approved account, resource, identity, and business dependency context.", gates: ["Account approval", "Role review", "Data minimization"], work: "Cloud region and provider dependency review" },
  { id: "api", label: "API assurance", icon: RadioTower, objective: "Coordinate approved API ownership, evidence, remediation, and retest evidence.", gates: ["API inventory", "Owner attestation", "Test account policy"], work: "Service contract and evidence freshness review" },
  { id: "mobile", label: "Mobile assurance", icon: Smartphone, objective: "Track authorized application, release, backend dependency, and privacy review context.", gates: ["Release approval", "Test build", "Privacy profile"], work: "Release-to-service dependency mapping" },
  { id: "wireless", label: "Wireless & field", icon: Wifi, objective: "Plan authorized site, work-zone, equipment, and coordination evidence.", gates: ["Site authorization", "Safety plan", "Field roster"], work: "GIS work-zone and onsite coverage review" },
  { id: "physical", label: "Physical & facilities", icon: Map, objective: "Coordinate permitted facilities context, access transitions, and response owners.", gates: ["Facility approval", "Access boundary", "Privacy review"], work: "Floor-plan route and access-transition planning" },
  { id: "redteam", label: "Red-team exercise", icon: BriefcaseBusiness, objective: "Govern a leadership-approved exercise with defined objectives, stops, and deconfliction.", gates: ["Executive authorization", "Rules of engagement", "Deconfliction plan"], work: "Objective-to-evidence and executive reporting coordination" },
] as const;

const services = [
  { name: "Customer API control plane", owner: "Application Security", classification: "Confidential synthetic", criticality: "Tier 1", lifecycle: "Active", provider: "Aurora Compute" },
  { name: "Telemetry relay service", owner: "Infrastructure", classification: "Internal synthetic", criticality: "Tier 1", lifecycle: "Active", provider: "Northstar Relay" },
  { name: "Partner gateway", owner: "Platform Engineering", classification: "Restricted synthetic", criticality: "Tier 2", lifecycle: "Review due", provider: "Helix edge" },
  { name: "Regional reporting path", owner: "Risk Operations", classification: "Internal synthetic", criticality: "Tier 3", lifecycle: "Planned", provider: "Solstice Transit" },
];

export default function CampaignAndOwnershipPlanner() {
  const [activeId, setActiveId] = useState<(typeof campaigns)[number]["id"]>("external");
  const active = campaigns.find((campaign) => campaign.id === activeId) ?? campaigns[0];
  const Icon = active.icon;
  return <section className="mt-4 atlas-surface p-4"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-start"><div><p className="eyebrow">ENGAGEMENT DESIGN & SERVICE OWNERSHIP</p><h3 className="mt-1 font-['Barlow_Condensed'] text-2xl font-semibold tracking-[.07em] text-white">CAMPAIGN PLANNER</h3><p className="mt-1 max-w-3xl text-xs leading-5 text-white/52">Choose an assessment track, establish its authorization gates, then link synthetic service ownership, business criticality, data classification, lifecycle, providers, and remediation handoff before activity begins.</p></div><span className="atlas-status">No execution from planner</span></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[.8fr_1.2fr]"><div className="grid grid-cols-2 gap-2 sm:grid-cols-4 xl:grid-cols-2">{campaigns.map((campaign) => { const CampaignIcon = campaign.icon; const selected = campaign.id === active.id; return <button key={campaign.id} onClick={() => setActiveId(campaign.id)} className={`rounded-lg border p-2.5 text-left transition-colors ${selected ? "border-[#e8b760]/45 bg-[#e8b760]/[.09]" : "border-white/8 bg-black/20 hover:border-white/20"}`}><CampaignIcon size={16} className={selected ? "text-[#f2cb82]" : "text-[#b9c7ff]"}/><p className="mt-2 text-[11px] font-medium text-white/72">{campaign.label}</p></button>})}</div>
      <div className="rounded-lg border border-[#e8b760]/22 bg-black/20 p-4"><div className="flex items-start gap-3"><div className="rounded-lg bg-[#e8b760]/10 p-2 text-[#f2cb82]"><Icon size={19}/></div><div><p className="text-sm font-semibold text-white/82">{active.label} assessment track</p><p className="mt-1 text-xs leading-5 text-white/55">{active.objective}</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div><p className="text-[9px] uppercase tracking-[.14em] text-white/38">Required gates</p><div className="mt-2 grid gap-1.5">{active.gates.map((gate) => <div key={gate} className="flex items-center gap-2 rounded border border-white/8 px-2 py-1.5 text-[10px] text-white/60"><CheckCircle2 size={12} className="text-[#f2cb82]"/>{gate}</div>)}</div></div><div><p className="text-[9px] uppercase tracking-[.14em] text-white/38">Decision work</p><div className="mt-2 rounded border border-white/8 bg-black/20 p-2 text-[10px] leading-4 text-white/58">{active.work}<p className="mt-2 text-[#b9c7ff]">Synthetic demonstration only · analyst confirmation required.</p></div></div></div></div></div>
    <div className="mt-4"><div className="flex items-center justify-between"><p className="eyebrow">BUSINESS-SERVICE OWNERSHIP REGISTER</p><span className="text-[10px] text-white/40">Synthetic data classification and ownership model</span></div><div className="mt-2 overflow-x-auto rounded-lg border border-white/8"><table className="w-full min-w-[760px] text-left text-[10px]"><thead className="border-b border-white/8 bg-black/20 text-[9px] uppercase tracking-[.12em] text-white/35"><tr><th className="px-3 py-2.5 font-medium">Business service</th><th className="px-3 py-2.5 font-medium">Accountable owner</th><th className="px-3 py-2.5 font-medium">Data class</th><th className="px-3 py-2.5 font-medium">Criticality</th><th className="px-3 py-2.5 font-medium">Lifecycle</th><th className="px-3 py-2.5 font-medium">Provider / handoff</th></tr></thead><tbody>{services.map((service) => <tr key={service.name} className="border-b border-white/[.055] last:border-0"><td className="px-3 py-2.5 font-medium text-white/76">{service.name}</td><td className="px-3 py-2.5 text-white/58">{service.owner}</td><td className="px-3 py-2.5 text-[#b9c7ff]">{service.classification}</td><td className="px-3 py-2.5 text-[#f2cb82]">{service.criticality}</td><td className="px-3 py-2.5 text-white/56">{service.lifecycle}</td><td className="px-3 py-2.5"><span className="inline-flex items-center gap-1 text-white/56">{service.provider}<ChevronRight size={11} className="text-[#f2cb82]"/>Remediation owner</span></td></tr>)}</tbody></table></div></div>
  </section>;
}
