import { BadgeCheck, Building2, FileCheck2, FileStack, Landmark, LockKeyhole, ShieldCheck, Stamp, UsersRound } from "lucide-react";
import { useState } from "react";

const audiences = [
  { id: "executive", label: "Executive sponsor", content: "Decision summary, risk concentration, approved remediation commitments, exceptions, and funding implications.", approval: "Sponsor acknowledgment" },
  { id: "technical", label: "Technical remediation team", content: "Finding details, evidence references, ownership, target dates, validation notes, and retest outcomes.", approval: "Engineering owner acceptance" },
  { id: "risk", label: "Risk & compliance", content: "Scope, authorization, evidence custody, exceptions, control mapping, retention, and audit ledger references.", approval: "Risk owner attestation" },
  { id: "client", label: "Client read-only workspace", content: "Redaction-aware delivery set with approved report versions and time-bounded share records.", approval: "Delivery manager release" },
] as const;

const commitments = [
  { finding: "Edge exposure variance", owner: "Platform Engineering", due: "2026-09-12", status: "In progress", retest: "Evidence requested" },
  { finding: "Geographic evidence register", owner: "Lead Analyst", due: "2026-09-05", status: "Review", retest: "Not applicable" },
  { finding: "Synthetic retest window", owner: "Assessment Manager", due: "2026-09-18", status: "Planned", retest: "Awaiting owner" },
];

const governance = [
  { label: "SSO & role lifecycle", status: "Private prerequisite", icon: UsersRound },
  { label: "Tenant isolation & residency", status: "Private prerequisite", icon: Building2 },
  { label: "Legal hold & retention", status: "Configured policy model", icon: Landmark },
  { label: "Audit export & incident process", status: "Readiness model", icon: ShieldCheck },
];

export default function ClientDeliveryGovernanceCenter() {
  const [audienceId, setAudienceId] = useState<(typeof audiences)[number]["id"]>("executive");
  const audience = audiences.find((item) => item.id === audienceId) ?? audiences[0];
  return <section className="mt-4 atlas-surface p-4"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-start"><div><p className="eyebrow">CLIENT DELIVERY & ENTERPRISE GOVERNANCE</p><h3 className="mt-1 font-['Barlow_Condensed'] text-2xl font-semibold tracking-[.07em] text-white">DELIVERY ASSURANCE CENTER</h3><p className="mt-1 max-w-3xl text-xs leading-5 text-white/52">Prepare audience-specific, redaction-aware delivery sets; coordinate remediation commitments and retest evidence; and surface the governance prerequisites required for a private multi-tenant deployment.</p></div><span className="atlas-status">Approval before release</span></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[.8fr_1.2fr]"><div className="grid gap-2">{audiences.map((item) => { const selected = item.id === audience.id; return <button key={item.id} onClick={() => setAudienceId(item.id)} className={`rounded-lg border p-3 text-left ${selected ? "border-[#e8b760]/45 bg-[#e8b760]/[.08]" : "border-white/8 bg-black/20 hover:border-white/20"}`}><p className="text-[11px] font-medium text-white/73">{item.label}</p><p className="mt-1 text-[9px] text-white/40">{item.approval}</p></button>})}</div><div className="rounded-lg border border-white/8 bg-black/20 p-4"><div className="flex items-start gap-3"><div className="rounded-lg bg-[#e8b760]/10 p-2 text-[#f2cb82]"><FileStack size={19}/></div><div><p className="text-sm font-semibold text-white/80">{audience.label} delivery set</p><p className="mt-1 text-[11px] leading-5 text-white/58">{audience.content}</p></div></div><div className="mt-4 grid gap-2 sm:grid-cols-3">{[["Report version", "Draft 0.4 · synthetic"],["Evidence bundle", "Metadata only"],["Release condition", audience.approval]].map(([label, value]) => <div key={label} className="rounded border border-white/8 p-2.5"><p className="text-[9px] uppercase tracking-[.12em] text-white/35">{label}</p><p className="mt-1 text-[11px] text-white/67">{value}</p></div>)}</div><div className="mt-4 flex items-center justify-between gap-3 rounded border border-[#e8b760]/18 bg-[#e8b760]/[.045] px-3 py-2"><p className="flex items-center gap-2 text-[10px] leading-4 text-white/57"><LockKeyhole size={14} className="shrink-0 text-[#f2cb82]"/>Public build: delivery release is intentionally locked. Private tenants require approved redaction, audience, expiry, and audit record.</p><button disabled className="atlas-action shrink-0 text-xs opacity-50">Release locked</button></div></div></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><section className="rounded-lg border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><FileCheck2 size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/76">Remediation commitments & retest coordination</p></div><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-[10px]"><thead className="border-b border-white/8 text-[9px] uppercase tracking-[.12em] text-white/35"><tr><th className="pb-2 font-medium">Work item</th><th className="pb-2 font-medium">Accountable owner</th><th className="pb-2 font-medium">Target</th><th className="pb-2 font-medium">Commitment</th><th className="pb-2 font-medium">Retest</th></tr></thead><tbody>{commitments.map((item) => <tr key={item.finding} className="border-b border-white/[.055] last:border-0"><td className="py-2.5 text-white/75">{item.finding}</td><td className="py-2.5 text-white/56">{item.owner}</td><td className="py-2.5 text-[#b9c7ff]">{item.due}</td><td className="py-2.5 text-[#f2cb82]">{item.status}</td><td className="py-2.5 text-white/55">{item.retest}</td></tr>)}</tbody></table></div><p className="mt-3 text-[10px] text-white/42">A private workflow would link each commitment to a remediation owner, evidence condition, ticket reference, retest analyst, and signed closure decision.</p></section>
      <section className="rounded-lg border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><Stamp size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/76">Enterprise governance posture</p></div><div className="mt-3 grid gap-2">{governance.map((item) => { const ItemIcon = item.icon; return <div key={item.label} className="flex items-center gap-3 rounded border border-white/8 p-2.5"><ItemIcon size={15} className="text-[#b9c7ff]"/><div><p className="text-[11px] text-white/71">{item.label}</p><p className="mt-1 text-[9px] text-white/42">{item.status}</p></div><BadgeCheck size={13} className="ml-auto text-[#f2cb82]"/></div>})}</div></section></div>
  </section>;
}
