import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { BadgeCheck, Cable, FileWarning, ShieldCheck, Stamp, Waypoints } from "lucide-react";
import { useState } from "react";

export default function DurableGovernanceRecords() {
  const { user } = useAuth();
  const utils = trpc.useUtils();
  const snapshot = trpc.workspace.operationsSnapshot.useQuery({ engagementId: 1 }, { enabled: Boolean(user) });
  const invalidate = () => utils.workspace.operationsSnapshot.invalidate({ engagementId: 1 });
  const createExposure = trpc.workspace.createExposureValidation.useMutation({ onSuccess: invalidate });
  const reviewExposure = trpc.workspace.reviewExposureValidation.useMutation({ onSuccess: invalidate });
  const createException = trpc.workspace.createDeliveryException.useMutation({ onSuccess: invalidate });
  const createAttestation = trpc.workspace.createDeliveryAttestation.useMutation({ onSuccess: invalidate });
  const createConnector = trpc.workspace.createConnectorReview.useMutation({ onSuccess: invalidate });
  const createCompliance = trpc.workspace.createComplianceEvidence.useMutation({ onSuccess: invalidate });
  const [exposureTitle, setExposureTitle] = useState("Approved synthetic exposure validation");
  const [exceptionTitle, setExceptionTitle] = useState("Synthetic delivery exception");
  const [attestationNotes, setAttestationNotes] = useState("Synthetic retest sign-off reviewed by accountable analyst.");
  const [connectorOwner, setConnectorOwner] = useState("Private Connector Owner");
  const [complianceControl, setComplianceControl] = useState("SSO and role-lifecycle evidence");
  const data = snapshot.data;
  if (!user) return <section className="mt-4 rounded-lg border border-white/8 bg-black/20 p-4"><p className="eyebrow">DURABLE GOVERNANCE RECORDS</p><p className="mt-2 text-xs text-white/48">Sign in to stage private workflow metadata. The public demonstration does not create governed records.</p></section>;
  return <section className="mt-4 atlas-surface p-4"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-start"><div><p className="eyebrow">DURABLE PRIVATE WORKFLOW RECORDS</p><h3 className="mt-1 font-['Barlow_Condensed'] text-2xl font-semibold tracking-[.07em] text-white">GOVERNED DECISION LEDGER</h3><p className="mt-1 max-w-3xl text-xs leading-5 text-white/52">Persisted records attach reviewer identity, confidence transition, delivery exception, attestation, connector review, compliance evidence, and audit history to a scoped engagement. Public records remain synthetic metadata.</p></div><span className="atlas-status">{snapshot.isLoading ? "Loading ledger" : "Private actions protected"}</span></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-2"><section className="rounded-lg border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><Waypoints size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/75">Exposure validation records</p></div><div className="mt-3 flex gap-2"><input value={exposureTitle} onChange={(event) => setExposureTitle(event.target.value)} className="h-8 min-w-0 flex-1 rounded border border-white/10 bg-black/25 px-2 text-xs text-white"/><button onClick={() => createExposure.mutate({ engagementId: 1, title: exposureTitle, gisZone: "Northstar relay campus", evidenceReference: "Synthetic approved evidence checkpoint" })} disabled={createExposure.isPending} className="atlas-action text-xs disabled:opacity-50">Stage</button></div><div className="mt-3 grid gap-1.5">{data?.exposureValidations?.length ? data.exposureValidations.slice(0, 4).map((item) => <div key={item.id} className="rounded border border-white/8 p-2 text-[10px]"><div className="flex justify-between gap-2"><span className="text-white/70">{item.title}</span><span className="text-[#f2cb82]">{item.validationState}</span></div><p className="mt-1 text-white/42">{item.gisZone} · {item.confidence}</p><button onClick={() => reviewExposure.mutate({ engagementId: 1, validationId: item.id, validationState: "analyst-confirmed", confidence: "high" })} className="mt-2 text-[#bde0b5]">Confirm with audit</button></div>) : <p className="text-[10px] text-white/42">No persisted exposure-validation records yet.</p>}</div></section>
      <section className="rounded-lg border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><FileWarning size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/75">Delivery exceptions & attestations</p></div><div className="mt-3 grid gap-2 sm:grid-cols-2"><div><input value={exceptionTitle} onChange={(event) => setExceptionTitle(event.target.value)} className="h-8 w-full rounded border border-white/10 bg-black/25 px-2 text-xs text-white"/><button onClick={() => createException.mutate({ engagementId: 1, title: exceptionTitle, rationale: "Synthetic exception staged for approved private delivery review." })} className="atlas-action mt-2 text-xs">Request exception</button></div><div><input value={attestationNotes} onChange={(event) => setAttestationNotes(event.target.value)} className="h-8 w-full rounded border border-white/10 bg-black/25 px-2 text-xs text-white"/><button onClick={() => createAttestation.mutate({ engagementId: 1, audience: "technical", attestationType: "retest-sign-off", notes: attestationNotes })} className="atlas-action mt-2 text-xs">Record sign-off</button></div></div><div className="mt-3 grid gap-1.5">{data?.deliveryExceptions?.map((item) => <p key={item.id} className="rounded border border-white/8 px-2 py-1.5 text-[10px] text-white/58">Exception · {item.title} · <span className="text-[#f2cb82]">{item.exceptionStatus}</span></p>)}{data?.deliveryAttestations?.map((item) => <p key={item.id} className="rounded border border-white/8 px-2 py-1.5 text-[10px] text-white/58">Attestation · {item.attestationType} / {item.audience} · <span className="text-[#bde0b5]">{item.attestationState}</span></p>)}{!data?.deliveryExceptions?.length && !data?.deliveryAttestations?.length && <p className="text-[10px] text-white/42">No delivery exception or attestation records yet.</p>}</div></section></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-2"><section className="rounded-lg border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><Cable size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/75">Connector security review</p></div><div className="mt-3 flex gap-2"><input value={connectorOwner} onChange={(event) => setConnectorOwner(event.target.value)} className="h-8 min-w-0 flex-1 rounded border border-white/10 bg-black/25 px-2 text-xs text-white"/><button onClick={() => createConnector.mutate({ engagementId: 1, adapterType: "cmdb", connectorOwner, dataResidency: "Approved private region", evidenceJson: { synthetic: true, noConnection: true, reviewChecklist: "pending" } })} className="atlas-action text-xs">Stage CMDB review</button></div><div className="mt-3 grid gap-1.5">{data?.connectorReviews?.length ? data.connectorReviews.map((item) => <p key={item.id} className="rounded border border-white/8 px-2 py-1.5 text-[10px] text-white/58">{item.adapterType} · {item.connectorOwner} · <span className="text-[#f2cb82]">{item.reviewStatus}</span></p>) : <p className="text-[10px] text-white/42">No connector reviews have been staged.</p>}</div></section>
      <section className="rounded-lg border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><ShieldCheck size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/75">Compliance evidence posture</p></div><div className="mt-3 flex gap-2"><input value={complianceControl} onChange={(event) => setComplianceControl(event.target.value)} className="h-8 min-w-0 flex-1 rounded border border-white/10 bg-black/25 px-2 text-xs text-white"/><button onClick={() => createCompliance.mutate({ engagementId: 1, controlName: complianceControl, evidenceReference: "Synthetic private readiness evidence reference", accountableOwner: "Governance Owner" })} className="atlas-action text-xs">Stage evidence</button></div><div className="mt-3 grid gap-1.5">{data?.complianceEvidence?.length ? data.complianceEvidence.map((item) => <p key={item.id} className="rounded border border-white/8 px-2 py-1.5 text-[10px] text-white/58">{item.controlName} · {item.accountableOwner} · <span className="text-[#b9c7ff]">{item.controlStatus}</span></p>) : <p className="text-[10px] text-white/42">No compliance evidence records have been staged.</p>}</div></section></div>
    <p className="mt-4 flex items-center gap-2 text-[10px] text-white/42"><Stamp size={13} className="text-[#e8b760]"/>Every protected mutation is role-gated and appends a synthetic audit event. External adapters remain disconnected in the public demonstration.</p>
  </section>;
}
