import { Accessibility, Activity, BookOpenCheck, Braces, Gauge, HeartPulse, PackageCheck, RotateCcw, ShieldCheck, TestTube2 } from "lucide-react";
import { useMemo, useState } from "react";

const qualityItems = [
  { id: "health", label: "Product health & observability", detail: "Structured application events, request health, client errors, operational SLOs, and privacy-safe diagnostics.", icon: HeartPulse },
  { id: "api", label: "API & webhook contracts", detail: "Versioned contract, schema examples, tenant scope, rate limits, signature policy, deprecation, and replay protection.", icon: Braces },
  { id: "recovery", label: "Backup & recovery evidence", detail: "Encrypted backup policy, recovery objectives, restore-drill outcome, incident communication, and owner escalation.", icon: RotateCcw },
  { id: "accessibility", label: "Accessibility & responsive review", detail: "Keyboard operation, focus visibility, semantic landmarks, contrast, reduced motion, mobile density, and table overflow review.", icon: Accessibility },
  { id: "testing", label: "Quality test matrix", detail: "Unit, router guard, render, integration, visual, authorization, recovery, and regression coverage by release.", icon: TestTube2 },
  { id: "release", label: "Release & architecture discipline", detail: "Change review, migration review, ADR, CI/CD gate, release checklist, rollback checkpoint, and post-release watch.", icon: PackageCheck },
] as const;

export default function EngineeringQualityCenter() {
  const [done, setDone] = useState<Record<string, boolean>>({});
  const completed = Object.values(done).filter(Boolean).length;
  const pct = useMemo(() => Math.round((completed / qualityItems.length) * 100), [completed]);
  return <section className="mt-4 atlas-surface p-4"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-start"><div><p className="eyebrow">ENGINEERING QUALITY, RELIABILITY & RELEASE READINESS</p><h3 className="mt-1 font-['Barlow_Condensed'] text-2xl font-semibold tracking-[.07em] text-white">PRODUCT HEALTH CONTROL ROOM</h3><p className="mt-1 max-w-3xl text-xs leading-5 text-white/52">Maintain a verifiable quality posture for private deployment. These controls capture readiness planning; they do not claim external certification or operate infrastructure outside this managed project.</p></div><span className="atlas-status">{completed}/{qualityItems.length} release controls</span></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[.7fr_1.3fr]"><div className="rounded-lg border border-[#e8b760]/18 bg-[#e8b760]/[.045] p-4"><div className="flex items-center gap-3"><div className="relative flex h-16 w-16 items-center justify-center rounded-full border-2 border-[#e8b760]/45" style={{ background: `conic-gradient(#e8b760 ${pct}%, rgba(255,255,255,.08) 0)` }}><div className="flex h-12 w-12 items-center justify-center rounded-full bg-[#0a0907] text-sm font-semibold text-[#f2cb82]">{pct}%</div></div><div><p className="text-sm font-semibold text-white/80">Release quality posture</p><p className="mt-1 text-[11px] leading-5 text-white/52">A release gate must be evidenced in CI and operations—not simply checked in an interface.</p></div></div><div className="mt-4 grid grid-cols-2 gap-2">{[["Client budget", "< 250KB route goal"],["Error policy", "No private data in logs"],["Recovery", "Restore drill required"],["SLO", "Tenant-defined"]].map(([label, value]) => <div key={label} className="rounded border border-white/8 bg-black/20 p-2"><p className="text-[9px] uppercase tracking-[.12em] text-white/35">{label}</p><p className="mt-1 text-[10px] text-white/66">{value}</p></div>)}</div></div>
      <div className="grid gap-2 sm:grid-cols-2">{qualityItems.map((item) => { const Icon = item.icon; return <label key={item.id} className={`flex gap-3 rounded-lg border p-3 ${done[item.id] ? "border-[#83a77c]/30 bg-[#83a77c]/[.05]" : "border-white/8 bg-black/20 hover:border-white/20"}`}><input type="checkbox" checked={Boolean(done[item.id])} onChange={(event) => setDone((current) => ({ ...current, [item.id]: event.target.checked }))} className="mt-0.5 accent-[#e8b760]"/><div><div className="flex items-center gap-2"><Icon size={15} className={done[item.id] ? "text-[#bde0b5]" : "text-[#b9c7ff]"}/><p className="text-[11px] font-medium text-white/75">{item.label}</p></div><p className="mt-2 text-[10px] leading-4 text-white/48">{item.detail}</p></div></label>})}</div></div>
    <p className="mt-4 flex items-center gap-2 text-[10px] text-white/42"><Gauge size={13} className="text-[#e8b760]"/><BookOpenCheck size={13} className="text-[#e8b760]"/><ShieldCheck size={13} className="text-[#e8b760]"/>Use the engineering readiness guide and checkpoint history as part of the release record; validate all claims against the target private environment before go-live.</p>
  </section>;
}
