import { Activity, BadgeCheck, Braces, Building2, KeyRound, LockKeyhole, RefreshCw, ShieldAlert, ShieldCheck, UsersRound } from "lucide-react";
import { useMemo, useState } from "react";

const readinessItems = [
  { id: "sso", title: "SSO / SAML / OIDC", detail: "Tenant-approved identity provider, verified domains, role claims, and enforced MFA.", icon: KeyRound, category: "Identity" },
  { id: "scim", title: "SCIM lifecycle", detail: "Joiner/mover/leaver provisioning, role deprovisioning, and ownership recertification.", icon: UsersRound, category: "Identity" },
  { id: "breakglass", title: "Break-glass access", detail: "Dual approval, time bound, reason capture, and immutable escalation audit trail.", icon: ShieldAlert, category: "Access" },
  { id: "tenant", title: "Tenant isolation & residency", detail: "Logical segregation, regional storage selection, encryption ownership, and cross-tenant controls.", icon: Building2, category: "Data" },
  { id: "session", title: "Session & device audit", detail: "Sign-in, session, device, and privileged-action events exported to the tenant audit ledger.", icon: Activity, category: "Audit" },
  { id: "recovery", title: "Backup & recovery", detail: "Encrypted backups, recovery objectives, restore drills, and incident communication plan.", icon: RefreshCw, category: "Resilience" },
  { id: "api", title: "Private API boundary", detail: "Versioned contracts, short-lived scoped tokens, rate limits, webhook signatures, and tenant allow-lists.", icon: Braces, category: "Platform" },
] as const;

export default function EnterpriseReadinessCenter() {
  const [complete, setComplete] = useState<Record<string, boolean>>({ sso: false, scim: false, breakglass: false, tenant: false, session: false, recovery: false, api: false });
  const done = Object.values(complete).filter(Boolean).length;
  const score = useMemo(() => Math.round((done / readinessItems.length) * 100), [done]);
  return <section className="mt-4 atlas-surface p-4"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-start"><div><p className="eyebrow">ENTERPRISE IDENTITY, TENANCY & PLATFORM READINESS</p><h3 className="mt-1 font-['Barlow_Condensed'] text-2xl font-semibold tracking-[.07em] text-white">PRIVATE TENANT ASSURANCE GATE</h3><p className="mt-1 max-w-3xl text-xs leading-5 text-white/52">Use this implementation checklist before a private tenant processes organization data. It stages readiness evidence only; it does not configure identity providers, issue tokens, or retain credentials in the public build.</p></div><span className="atlas-status">{done}/{readinessItems.length} readiness controls</span></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[.7fr_1.3fr]"><div className="rounded-lg border border-[#e8b760]/18 bg-[#e8b760]/[.045] p-4"><div className="flex items-center gap-3"><div className="relative flex h-16 w-16 items-center justify-center rounded-full border-2 border-[#e8b760]/45" style={{ background: `conic-gradient(#e8b760 ${score}%, rgba(255,255,255,.08) 0)` }}><div className="flex h-12 w-12 items-center justify-center rounded-full bg-[#0a0907] text-sm font-semibold text-[#f2cb82]">{score}%</div></div><div><p className="text-sm font-semibold text-white/80">Readiness score</p><p className="mt-1 text-[11px] leading-5 text-white/52">A planning indicator, not a certification. Completion still requires independent security, legal, privacy, and customer approval.</p></div></div><div className="mt-4 rounded border border-white/8 bg-black/20 p-3"><p className="flex items-center gap-2 text-[10px] leading-4 text-white/56"><LockKeyhole size={14} className="text-[#f2cb82]"/>Credential capture and IdP connection stay disabled until a private deployment has a tenant, approved secret manager, and documented authorization.</p></div></div>
      <div className="grid gap-2 sm:grid-cols-2">{readinessItems.map((item) => { const Icon = item.icon; return <label key={item.id} className={`flex cursor-pointer gap-3 rounded-lg border p-3 ${complete[item.id] ? "border-[#83a77c]/35 bg-[#83a77c]/[.06]" : "border-white/8 bg-black/20 hover:border-white/20"}`}><input type="checkbox" checked={complete[item.id]} onChange={(event) => setComplete((current) => ({ ...current, [item.id]: event.target.checked }))} className="mt-0.5 accent-[#e8b760]"/><div className="min-w-0"><div className="flex items-center gap-2"><Icon size={15} className={complete[item.id] ? "text-[#bde0b5]" : "text-[#b9c7ff]"}/><p className="text-[11px] font-medium text-white/76">{item.title}</p></div><p className="mt-1 text-[9px] uppercase tracking-[.12em] text-[#e8b760]/80">{item.category}</p><p className="mt-1 text-[10px] leading-4 text-white/48">{item.detail}</p></div></label>})}</div></div>
    <p className="mt-3 flex items-center gap-2 text-[10px] text-white/42"><BadgeCheck size={13} className="text-[#e8b760]"/>A private production release should require security architecture approval, privacy/DPA approval, threat model sign-off, a successful restore drill, and customer acceptance before connector activation.</p>
  </section>;
}
