import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, ClipboardCheck, FileKey2, MessageSquareText, ShieldCheck, UsersRound } from "lucide-react";
import { useEffect, useState } from "react";

type ScopeState = "draft" | "pending-review" | "approved" | "expired" | "blocked";
type ImportGate = "review-required" | "approved" | "blocked";
type Retention = "demo-session" | "engagement" | "legal-hold" | "restricted";
type Redaction = "synthetic-demo" | "internal" | "client" | "restricted";

export default function GovernanceCollaborationPanel() {
  const { user } = useAuth();
  const utils = trpc.useUtils();
  const snapshot = trpc.workspace.operationsSnapshot.useQuery({ engagementId: 1 }, { enabled: Boolean(user) });
  const [message, setMessage] = useState("");
  const [comment, setComment] = useState("");
  const [memberId, setMemberId] = useState("");
  const [memberRole, setMemberRole] = useState<"manager" | "analyst" | "reviewer" | "read-only">("analyst");
  const [scopeApprovalStatus, setScopeApprovalStatus] = useState<ScopeState>("pending-review");
  const [importGateStatus, setImportGateStatus] = useState<ImportGate>("review-required");
  const [retentionProfile, setRetentionProfile] = useState<Retention>("engagement");
  const [redactionProfile, setRedactionProfile] = useState<Redaction>("synthetic-demo");
  const [watermarkText, setWatermarkText] = useState("SYNTHETIC · AUTHORIZED DEMONSTRATION");
  const [templateName, setTemplateName] = useState("Authorized GIS assessment");
  const [clientName, setClientName] = useState("Synthetic client workspace");
  const [clientCode, setClientCode] = useState("CW-SYNTH-01");
  const refresh = () => utils.workspace.operationsSnapshot.invalidate({ engagementId: 1 });
  const governance = trpc.workspace.updateGovernance.useMutation({ onSuccess: () => { refresh(); setMessage("Governance state saved with an immutable audit event."); }, onError: () => setMessage("Governance update was blocked by the current engagement role."), });
  const addComment = trpc.workspace.addComment.useMutation({ onSuccess: () => { refresh(); setComment(""); setMessage("Review comment appended to the engagement ledger."); }, onError: () => setMessage("Comment could not be recorded."), });
  const reviewTask = trpc.workspace.reviewTask.useMutation({ onSuccess: () => { refresh(); setMessage("Task review state recorded and audited."); }, onError: () => setMessage("Task review requires an active reviewer or manager role."), });
  const approveReport = trpc.workspace.approveReport.useMutation({ onSuccess: () => { refresh(); setMessage("Report approval recorded."); }, onError: () => setMessage("Report approval requires an active reviewer or manager role."), });
  const shareReport = trpc.workspace.createReadOnlyShare.useMutation({ onSuccess: (result) => { refresh(); setMessage(`Read-only share token issued: ${result.token.slice(0, 12)}… Expires in 7 days.`); }, onError: () => setMessage("Read-only share could not be issued."), });
  const assignMember = trpc.workspace.assignMember.useMutation({ onSuccess: () => { refresh(); setMemberId(""); setMessage("Engagement membership assignment recorded."); }, onError: () => setMessage("Membership assignment requires an active manager role."), });
  const decideImport = trpc.workspace.decideImport.useMutation({ onSuccess: () => { refresh(); setMessage("Synthetic import approval gate decision recorded."); }, onError: () => setMessage("Import decision could not be recorded."), });
  const createTemplate = trpc.workspace.createTemplate.useMutation({ onSuccess: () => { refresh(); setMessage("Reusable engagement template recorded."); }, onError: () => setMessage("Template creation requires an active manager role."), });
  const createClientWorkspace = trpc.workspace.createClientWorkspace.useMutation({ onSuccess: () => { refresh(); setMessage("Synthetic client workspace recorded."); }, onError: () => setMessage("Client workspace creation requires administrator access."), });
  const markNotificationRead = trpc.workspace.markNotificationRead.useMutation({ onSuccess: () => refresh(), onError: () => setMessage("Notification state could not be updated."), });

  useEffect(() => {
    const current = snapshot.data?.governance;
    if (!current) return;
    setScopeApprovalStatus(current.scopeApprovalStatus);
    setImportGateStatus(current.importGateStatus);
    setRetentionProfile(current.retentionProfile);
    setRedactionProfile(current.redactionProfile);
    setWatermarkText(current.watermarkText);
  }, [snapshot.data?.governance]);

  if (!user) return <section className="mt-4 atlas-surface border-dashed p-4"><p className="eyebrow">GOVERNANCE & COLLABORATION</p><p className="mt-2 text-xs leading-5 text-white/52">Sign in to view private team assignments, scope approvals, evidence gates, review queues, approval records, and expiring read-only delivery shares. Public demonstration mode exposes no private operations data.</p></section>;
  if (snapshot.isLoading) return <section className="mt-4 atlas-surface p-4 text-xs text-[#f2cb82]">Loading authenticated governance, delivery, and collaboration state…</section>;
  if (snapshot.isError) return <section className="mt-4 atlas-surface border-[#ee7664]/30 p-4" role="alert"><p className="text-xs font-semibold text-[#ffab9d]">Private operations state is unavailable.</p><p className="mt-1 text-[11px] leading-5 text-white/52">Your account requires active engagement membership before private delivery data can be displayed.</p></section>;

  const data = snapshot.data ?? { tasks: [], geospatialArtifacts: [], reports: [], governance: undefined, members: [], comments: [], taskReviews: [], importDecisions: [], shareLinks: [], templates: [], clientWorkspaces: [], notifications: [], auditEvents: [] };
  const saveGovernance = () => governance.mutate({ engagementId: 1, scopeApprovalStatus, importGateStatus, dataOriginLabel: "synthetic-authorized-demo", retentionProfile, redactionProfile, watermarkText });
  const deadline = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000);
  return <section className="mt-4 atlas-surface p-4"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-start"><div><p className="eyebrow">GOVERNANCE, TEAM & DELIVERY CONTROLS</p><p className="mt-1 max-w-3xl text-xs leading-5 text-white/52">Role-aware operations for a synthetic authorized workspace. All decisions append audit events; read-only sharing is time-bounded and remains a delivery-record pattern rather than a public data endpoint.</p></div><span className="atlas-status">{data.governance?.scopeApprovalStatus ?? "draft"}</span></div>{message && <p className="mt-3 rounded border border-[#e8b760]/20 bg-[#e8b760]/[.05] px-3 py-2 text-[11px] text-[#f2cb82]" aria-live="polite">{message}</p>}
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.1fr_.9fr]">
      <div className="space-y-4"><section className="rounded-lg border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><ShieldCheck size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/80">Scope, import, retention, and redaction gate</p></div><div className="mt-3 grid gap-2 sm:grid-cols-2"><GovernanceSelect label="Scope approval" value={scopeApprovalStatus} onChange={(value) => setScopeApprovalStatus(value as ScopeState)} options={["draft", "pending-review", "approved", "expired", "blocked"]}/><GovernanceSelect label="Import gate" value={importGateStatus} onChange={(value) => setImportGateStatus(value as ImportGate)} options={["review-required", "approved", "blocked"]}/><GovernanceSelect label="Retention" value={retentionProfile} onChange={(value) => setRetentionProfile(value as Retention)} options={["demo-session", "engagement", "legal-hold", "restricted"]}/><GovernanceSelect label="Redaction" value={redactionProfile} onChange={(value) => setRedactionProfile(value as Redaction)} options={["synthetic-demo", "internal", "client", "restricted"]}/></div><label className="mt-2 block text-[10px] uppercase tracking-[.12em] text-white/42">Export watermark<input value={watermarkText} onChange={(event) => setWatermarkText(event.target.value)} className="mt-1 h-8 w-full rounded border border-white/10 bg-black/25 px-2 text-xs text-white"/></label><button onClick={saveGovernance} disabled={governance.isPending} className="atlas-action mt-3 text-xs disabled:opacity-50"><ShieldCheck size={13}/>{governance.isPending ? "Saving gate" : "Save governed lifecycle"}</button></section>
        <section className="rounded-lg border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><UsersRound size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/80">Team assignments</p></div><div className="mt-3 grid gap-2 sm:grid-cols-[1fr_130px_auto]"><input value={memberId} onChange={(event) => setMemberId(event.target.value)} inputMode="numeric" placeholder="Internal user ID" className="h-8 rounded border border-white/10 bg-black/25 px-2 text-xs text-white"/><select value={memberRole} onChange={(event) => setMemberRole(event.target.value as typeof memberRole)} className="h-8 rounded border border-white/10 bg-black/25 px-2 text-xs text-white"><option value="manager">Manager</option><option value="analyst">Analyst</option><option value="reviewer">Reviewer</option><option value="read-only">Read-only</option></select><button onClick={() => memberId && assignMember.mutate({ engagementId: 1, userId: Number(memberId), workspaceRole: memberRole, membershipStatus: "active" })} disabled={!memberId || assignMember.isPending} className="atlas-action text-xs disabled:opacity-50">Assign</button></div><div className="mt-3 grid gap-1.5">{data.members.length ? data.members.map((member) => <div key={member.id} className="flex items-center justify-between rounded border border-white/8 px-2 py-1.5 text-[10px] text-white/60"><span>User #{member.userId}</span><span>{member.workspaceRole} · {member.membershipStatus}</span></div>) : <p className="text-[10px] text-white/42">No private member assignments yet.</p>}</div></section>
      </div>
      <div className="space-y-4"><section className="rounded-lg border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><ClipboardCheck size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/80">Review & retest queue</p></div><div className="mt-3 grid gap-2">{data.tasks.length ? data.tasks.map((task) => <div key={task.id} className="rounded border border-white/8 p-2"><div className="flex items-center justify-between gap-2"><span className="text-[11px] text-white/78">{task.title}</span><span className="text-[9px] text-[#f2cb82]">{task.taskStatus}</span></div><div className="mt-2 flex gap-1.5"><button onClick={() => reviewTask.mutate({ engagementId: 1, taskId: task.id, reviewState: "requested", summary: "Review requested from governed operations queue." })} className="rounded border border-white/10 px-2 py-1 text-[9px] text-white/55">Request review</button><button onClick={() => reviewTask.mutate({ engagementId: 1, taskId: task.id, reviewState: "retest-signed-off", summary: "Synthetic retest sign-off recorded after reviewer confirmation." })} className="rounded border border-[#bde0b5]/25 px-2 py-1 text-[9px] text-[#bde0b5]">Retest sign-off</button></div></div>) : <p className="text-[10px] text-white/42">No persisted tasks are available for review.</p>}</div><p className="mt-2 text-[10px] text-white/45">{data.taskReviews.length} immutable review events recorded.</p></section>
        <section className="rounded-lg border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><FileKey2 size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/80">Report approval & read-only delivery</p></div><div className="mt-3 grid gap-2">{data.reports.length ? data.reports.map((report) => <div key={report.id} className="rounded border border-white/8 p-2"><div className="flex justify-between gap-2 text-[10px]"><span className="text-white/75">{report.reportType} · {report.redactionProfile}</span><span className="text-[#f2cb82]">{report.deliveryStatus}</span></div><div className="mt-2 flex gap-1.5"><button onClick={() => approveReport.mutate({ engagementId: 1, reportDeliveryId: report.id })} className="rounded border border-[#e8b760]/25 px-2 py-1 text-[9px] text-[#f2cb82]">Approve</button><button onClick={() => shareReport.mutate({ engagementId: 1, reportDeliveryId: report.id, expiresAt: deadline })} className="rounded border border-white/10 px-2 py-1 text-[9px] text-white/55">Issue read-only share</button></div></div>) : <p className="text-[10px] text-white/42">No persisted report deliveries are available.</p>}</div><p className="mt-2 text-[10px] text-white/45">{data.shareLinks.length} expiring read-only share records in the ledger.</p></section>
      </div>
    </div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1fr_.8fr]"><section className="rounded-lg border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><MessageSquareText size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/80">Analyst review comments</p></div><div className="mt-3 flex gap-2"><input value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Record a controlled analyst handoff or review note" className="h-8 min-w-0 flex-1 rounded border border-white/10 bg-black/25 px-2 text-xs text-white placeholder:text-white/35"/><button onClick={() => comment && addComment.mutate({ engagementId: 1, body: comment })} disabled={!comment || addComment.isPending} className="atlas-action text-xs disabled:opacity-50">Add note</button></div><div className="mt-3 grid gap-1.5">{data.comments.slice(0, 3).map((item) => <p key={item.id} className="rounded border border-white/8 px-2 py-1.5 text-[10px] text-white/60">User #{item.authorUserId} · {item.body}</p>)}{!data.comments.length && <p className="text-[10px] text-white/42">No collaboration comments have been recorded.</p>}</div></section><section className="rounded-lg border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><CheckCircle2 size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/80">Import promotion gate</p></div><p className="mt-2 text-[10px] leading-5 text-white/50">A default synthetic decision is available to demonstrate governed import promotion. Real target data is not accepted by this public project.</p><button onClick={() => decideImport.mutate({ engagementId: 1, artifactName: "synthetic-geojson-review.fixture", artifactHash: "0".repeat(64), disposition: "approved", rationale: "Synthetic-only fixture is in declared demonstration scope and has passed the visible review gate." })} disabled={decideImport.isPending} className="atlas-action mt-3 text-xs disabled:opacity-50">Record synthetic approval</button><p className="mt-3 text-[10px] text-white/45">{data.importDecisions.length} import decisions retained in the engagement ledger.</p></section></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-3"><section className="rounded-lg border border-white/8 bg-black/20 p-3"><p className="eyebrow">REUSABLE ENGAGEMENT TEMPLATE</p><input value={templateName} onChange={(event) => setTemplateName(event.target.value)} className="mt-3 h-8 w-full rounded border border-white/10 bg-black/25 px-2 text-xs text-white"/><button onClick={() => createTemplate.mutate({ name: templateName, description: "Synthetic authorized GIS assessment template with scope, evidence, and delivery gates.", templateJson: { synthetic: true, scopeGate: "pending-review", importGate: "review-required", reportRedaction: "synthetic-demo" } })} disabled={createTemplate.isPending} className="atlas-action mt-2 text-xs disabled:opacity-50">Save template</button><p className="mt-3 text-[10px] text-white/45">{data.templates.length} reusable templates retained.</p></section><section className="rounded-lg border border-white/8 bg-black/20 p-3"><p className="eyebrow">CLIENT / PROJECT WORKSPACE</p><input value={clientName} onChange={(event) => setClientName(event.target.value)} className="mt-3 h-8 w-full rounded border border-white/10 bg-black/25 px-2 text-xs text-white"/><input value={clientCode} onChange={(event) => setClientCode(event.target.value.toUpperCase())} className="mt-2 h-8 w-full rounded border border-white/10 bg-black/25 px-2 font-mono text-xs text-white"/><button onClick={() => createClientWorkspace.mutate({ displayName: clientName, workspaceCode: clientCode, classification: "synthetic" })} disabled={createClientWorkspace.isPending} className="atlas-action mt-2 text-xs disabled:opacity-50">Create workspace</button><p className="mt-3 text-[10px] text-white/45">{data.clientWorkspaces.length} owned workspaces retained.</p></section><section className="rounded-lg border border-white/8 bg-black/20 p-3"><p className="eyebrow">IN-APP NOTIFICATIONS</p><div className="mt-3 grid gap-1.5">{data.notifications.length ? data.notifications.slice(0, 3).map((item) => <button key={item.id} onClick={() => !item.readAt && markNotificationRead.mutate({ notificationId: item.id })} className={`rounded border px-2 py-1.5 text-left text-[10px] ${item.readAt ? "border-white/8 text-white/40" : "border-[#e8b760]/20 bg-[#e8b760]/[.04] text-white/65"}`}>{item.message}</button>) : <p className="text-[10px] text-white/42">Notifications are created by governed approvals, reviews, assignments, and delivery-share events.</p>}</div></section></div>
    <section className="mt-4 rounded-lg border border-white/8 bg-black/20 p-3"><p className="eyebrow">IMMUTABLE ENGAGEMENT AUDIT LEDGER</p><p className="mt-1 text-[10px] text-white/45">Read-only record of governed templates, assignments, decisions, reviews, approvals, and shares. The public demonstration exposes metadata only.</p><div className="mt-3 grid gap-1.5 md:grid-cols-2">{data.auditEvents.length ? data.auditEvents.slice(0, 8).map((event) => <div key={event.id} className="rounded border border-white/8 px-2 py-1.5 text-[10px] text-white/60"><span className="font-medium text-[#f2cb82]">{event.eventType}</span> · {event.summary}<span className="mt-1 block text-white/35">Actor #{event.actorUserId} · {new Date(event.createdAt).toLocaleString()}</span></div>) : <p className="text-[10px] text-white/42">No immutable audit events have been loaded for this engagement.</p>}</div></section>
  </section>;
}

function GovernanceSelect({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[] }) { return <label className="rounded border border-white/8 bg-black/15 p-2"><span className="text-[9px] uppercase tracking-[.12em] text-white/38">{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 w-full bg-transparent text-xs text-white outline-none">{options.map((option) => <option key={option} value={option} className="bg-[#0d0b08]">{option}</option>)}</select></label>; }
