import { trpc } from "@/lib/trpc";
import { ChevronDown, Copy, FileWarning, Upload } from "lucide-react";
import { GeoJSON, MapContainer, TileLayer } from "react-leaflet";

const formats = ["GeoJSON", "Coordinate CSV", "CSV", "Generic JSON", "Nmap XML", "Nuclei JSONL", "KML planning", "GPX waypoints", "STAC Item"] as const;
const formatMap = { "GeoJSON": "geojson", "Coordinate CSV": "coordinate-csv", "CSV": "csv", "Generic JSON": "json", "Nmap XML": "nmap-xml", "Nuclei JSONL": "nuclei-jsonl", "KML planning": "kml", "GPX waypoints": "gpx", "STAC Item": "stac-item" } as const;
const samples = {
  "GeoJSON": JSON.stringify({ type: "FeatureCollection", features: [{ type: "Feature", properties: { name: "edge.helix-labs.example" }, geometry: { type: "Point", coordinates: [-12.8, 44.9] } }, { type: "Feature", properties: { name: "production.real-target.example" }, geometry: { type: "Point", coordinates: [1, 1] } }] }, null, 2),
  "Coordinate CSV": "name,latitude,longitude,precision\nNorthstar Relay Campus,64.1012,-23.1098,synthetic\nAurora Compute Region,25.2014,48.2042,synthetic\nproduction.real-target.example,1,1,unknown",
  "CSV": "host,severity\nedge.helix-labs.example,high\nedge.helix-labs.example,high\nproduction.real-target.example,critical",
  "Generic JSON": JSON.stringify({ items: [{ name: "Aurora Compute Region" }, { name: "Northstar Relay Campus" }, { name: "production.real-target.example" }] }, null, 2),
  "Nmap XML": "<?xml version=\"1.0\"?><nmaprun><host><address addr=\"203.0.113.18\" addrtype=\"ipv4\"/></host><host><address addr=\"production.real-target.example\" addrtype=\"hostname\"/></host></nmaprun>",
  "Nuclei JSONL": "{\"host\":\"edge.helix-labs.example\"}\n{\"host\":\"EDGE.HELIX-LABS.EXAMPLE\"}\n{\"host\":\"production.real-target.example\"}",
  "KML planning": "<kml><Document><Placemark><name>Northstar Relay Campus</name></Placemark><Placemark><name>production.real-target.example</name></Placemark></Document></kml>",
  "GPX waypoints": "<gpx><wpt lat=\"64.1012\" lon=\"-23.1098\"/><wpt lat=\"64.1031\" lon=\"-23.1054\"/></gpx>",
  "STAC Item": "{\"type\":\"Feature\",\"stac_version\":\"1.0.0\",\"id\":\"northstar-scene\",\"properties\":{\"name\":\"Northstar Relay Campus\",\"datetime\":\"2026-08-24T09:42:00Z\"}}",
};

export default function ImportWorkbench({ selected, setSelected }: { selected: string; setSelected: (value: string) => void }) {
  const preview = trpc.workspace.previewImport.useMutation();
  const format = selected as keyof typeof samples;
  const payload = samples[format];
  const result = preview.data;
  return <>
    <div className="mb-5 flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><p className="eyebrow">IMPORT CENTER / PREVIEW BEFORE COMMIT</p><h2 className="atlas-heading mt-1">VALIDATE & QUARANTINE</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/52">Each format executes against a distinct synthetic fixture. The parser returns explicit schema status, accepted rows, quarantined rows, and likely duplicates before any analyst approval or workspace write.</p></div><button onClick={() => preview.mutate({ format: formatMap[format], payload })} className="atlas-action atlas-action-primary"><Upload size={15}/> {preview.isPending ? "Validating artifact" : "Run preview"}</button></div>
    <div className="grid gap-4 xl:grid-cols-[.62fr_1.38fr]">
      <section className="atlas-surface p-4"><p className="eyebrow">SUPPORTED INPUTS</p><div className="mt-4 space-y-2">{formats.map((item) => <button key={item} onClick={() => setSelected(item)} className={`flex w-full items-center justify-between rounded-lg border px-3 py-3 text-left ${selected === item ? "border-[#e8b760]/45 bg-[#e8b760]/10 text-[#f2cb82]" : "border-white/8 bg-black/20 text-white/60"}`}><span className="text-xs font-medium">{item}</span><ChevronDown size={14} className="rotate-[-90deg]"/></button>)}</div><div className="mt-5 rounded-lg border border-[#e8b760]/20 bg-[#e8b760]/[.05] p-3 text-[11px] leading-5 text-white/58">Artifact bytes belong in secured object storage. The preview only exposes parser state, immutable artifact hash, provenance, and validation outcome.</div></section>
      <section className="atlas-surface overflow-hidden"><div className="flex items-center justify-between border-b border-white/10 px-4 py-3"><div><p className="eyebrow">{selected.toUpperCase()} FIXTURE</p><p className="mt-1 text-xs text-white/45">Payload changes with the selected parser.</p></div><button className="atlas-icon-button h-7 w-7" onClick={() => navigator.clipboard?.writeText(payload)} aria-label="Copy selected synthetic fixture"><Copy size={13}/></button></div><div className="grid gap-4 p-4 lg:grid-cols-[1.1fr_.9fr]"><div><pre className="max-h-[280px] overflow-auto rounded-lg border border-white/8 bg-black/35 p-3 text-[10px] leading-5 text-[#e6cb9a]">{payload}</pre>{format === "GeoJSON" && <GeoJsonGeometryPreview payload={payload}/>} {format === "Coordinate CSV" && <CoordinateCsvPreview payload={payload}/>}</div><div>{preview.isError ? <div role="alert" className="rounded-lg border border-[#ee7664]/30 bg-[#ee7664]/[.08] p-3 text-xs leading-5 text-[#ffab9d]">Preview service unavailable. The artifact was not added to the workspace.</div> : result ? <ValidationResult result={result} /> : <div className="rounded-lg border border-dashed border-white/15 p-5 text-center text-xs leading-5 text-white/45">Choose a format, inspect its fixture, and run a preview to see parser, schema, scope, duplicate, and quarantine results.</div>}</div></div><div className="border-t border-white/10 bg-black/20 px-4 py-3 text-xs text-white/48">Analyst approval is required before accepted artifact rows create workspace records. Quarantined rows remain excluded from atlas, graph, findings, and reports.</div></section>
    </div>
  </>;
}

function ValidationResult({ result }: { result: NonNullable<ReturnType<typeof trpc.workspace.previewImport.useMutation>["data"]> }) {
  return <><p className="eyebrow">VALIDATION RESULT</p><div className={`mt-3 rounded-lg border p-3 ${result.schemaValidation.valid ? "border-[#83a77c]/30 bg-[#83a77c]/[.07]" : "border-[#ee7664]/30 bg-[#ee7664]/[.07]"}`}><p className={`text-xs font-semibold ${result.schemaValidation.valid ? "text-[#bde0b5]" : "text-[#ffab9d]"}`}>Schema {result.schemaValidation.valid ? "valid" : "invalid"}</p><p className="mt-1 text-[11px] leading-5 text-white/58">{result.schemaValidation.message}</p></div><div className="mt-3 grid grid-cols-2 gap-2"><ResultMetric label="Parsed" value={String(result.totalRows)} good={result.schemaValidation.valid}/><ResultMetric label="Accepted" value={String(result.acceptedCount)} good/><ResultMetric label="Quarantined" value={String(result.quarantinedCount)} /><ResultMetric label="Duplicates" value={String(result.duplicateCandidates.length)} /></div><p className="mt-4 text-[10px] uppercase tracking-[.15em] text-white/38">Artifact SHA-256</p><p className="mt-1 break-all font-mono text-[10px] text-[#e6cb9a]">{result.artifactSha256}</p>{result.duplicateCandidates.length > 0 && <div className="mt-4 rounded-lg border border-[#e8b760]/25 bg-[#e8b760]/[.06] p-3"><p className="flex items-center gap-2 text-xs font-semibold text-[#f2cb82]"><FileWarning size={14}/> Analyst duplicate review</p>{result.duplicateCandidates.map((duplicate) => <p key={duplicate.subject} className="mt-2 text-[11px] text-white/58">{duplicate.subject} resembles {duplicate.matches}; no merge is performed automatically.</p>)}</div>}<div className="mt-4 rounded-lg border border-[#ee7664]/25 bg-[#ee7664]/[.05] p-3"><p className="text-xs font-medium text-[#ffad9d]">Quarantine disposition</p><p className="mt-2 text-[11px] leading-5 text-white/55">{result.rows.find((row) => !row.inScope)?.reason ?? "No out-of-scope records in this selected fixture."}</p></div></>;
}

function ResultMetric({ label, value, good = false }: { label: string; value: string; good?: boolean }) { return <div className="rounded-lg border border-white/8 bg-black/20 p-3"><p className="text-[10px] uppercase tracking-[.14em] text-white/38">{label}</p><p className={`mt-1 text-lg font-semibold ${good ? "text-[#bde0b5]" : "text-[#f0c678]"}`}>{value}</p></div>; }
function GeoJsonGeometryPreview({ payload }: { payload: string }) { const parsed = JSON.parse(payload) as { features?: Array<{ properties?: { name?: string }; geometry?: { type?: string; coordinates?: number[] } }> }; const features = parsed.features ?? []; const first = features[0]?.geometry?.coordinates; const center: [number, number] = typeof first?.[1] === "number" && typeof first?.[0] === "number" ? [first[1], first[0]] : [0, 0]; return <div className="mt-3 rounded-lg border border-[#87bfff]/25 bg-[#87bfff]/[.05] p-3"><p className="text-[10px] uppercase tracking-[.14em] text-[#c9d6ff]">Map-ready geometry display</p><div className="mt-2 h-36 overflow-hidden rounded border border-white/10"><MapContainer center={center} zoom={2} zoomControl={false} scrollWheelZoom={false} attributionControl={false} className="h-full w-full"><TileLayer url="https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png"/><GeoJSON data={parsed as GeoJSON.GeoJsonObject} style={() => ({ color: "#e8b760", weight: 2, fillColor: "#e8b760", fillOpacity: 0.22 })}/></MapContainer></div>{features.map((feature, index) => <p key={`${feature.properties?.name}-${index}`} className="mt-1 font-mono text-[10px] text-white/58">{feature.properties?.name ?? `feature-${index + 1}`} · {feature.geometry?.type} · {feature.geometry?.coordinates?.[1]}°, {feature.geometry?.coordinates?.[0]}°</p>)}<p className="mt-2 text-[10px] text-white/42">Previewed geometry remains synthetic and subject to scope quarantine before it can enter an atlas layer.</p></div>; }
function CoordinateCsvPreview({ payload }: { payload: string }) { const rows = payload.split("\n").slice(1).map((row) => row.split(",")); return <div className="mt-3 rounded-lg border border-[#87bfff]/25 bg-[#87bfff]/[.05] p-3"><p className="text-[10px] uppercase tracking-[.14em] text-[#c9d6ff]">Coordinate mapping</p>{rows.map((row) => <p key={row[0]} className="mt-1 font-mono text-[10px] text-white/58">{row[0]} · {row[1]}°, {row[2]}° · {row[3]}</p>)}<p className="mt-2 text-[10px] text-white/42">Coordinates are fixture-only and are validated against the declared synthetic scope before any governed promotion.</p></div>; }
