import { Accessibility, Globe2, Languages, MonitorSmartphone, MoonStar, ShieldCheck, Type } from "lucide-react";
import { useEffect, useState } from "react";

export default function InclusiveMobileReadiness() {
  const [locale,setLocale]=useState("English · en-US"); const [contrast,setContrast]=useState(false); const [textScale,setTextScale]=useState("Standard");
  useEffect(()=>{ document.documentElement.classList.toggle("atlas-high-contrast", contrast); return ()=>document.documentElement.classList.remove("atlas-high-contrast"); },[contrast]);
  return <section className="mt-4 atlas-surface p-4"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-start"><div><p className="eyebrow">INCLUSIVE EXPERIENCE & PRIVATE MOBILE READINESS</p><h3 className="mt-1 font-['Barlow_Condensed'] text-2xl font-semibold tracking-[.07em] text-white">ACCESSIBLE, LOCALIZED COMPANION DESIGN</h3><p className="mt-1 max-w-3xl text-xs leading-5 text-white/52">Prepare locale, readability, assistive-technology, and mobile-companion behavior without enrolling devices or collecting real field data. The public demonstration stores all preferences locally in the current session only.</p></div><span className="atlas-status">Inclusive design readiness</span></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-3"><div className="rounded border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><Languages size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/76">Locale & readability</p></div><select value={locale} onChange={e=>setLocale(e.target.value)} className="mt-3 h-9 w-full rounded border border-white/10 bg-black/25 px-2 text-xs text-white"><option>English · en-US</option><option>Arabic readiness · ar</option><option>French readiness · fr</option><option>Spanish readiness · es</option></select><select value={textScale} onChange={e=>setTextScale(e.target.value)} className="mt-2 h-9 w-full rounded border border-white/10 bg-black/25 px-2 text-xs text-white"><option>Standard</option><option>Large text</option><option>Extra large text</option></select><p className="mt-2 text-[10px] text-white/42">Private localization must include translated safety labels, locale-aware dates, pluralization, RTL validation, and human review.</p></div><div className="rounded border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><Accessibility size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/76">Accessibility controls</p></div><label className="mt-3 flex gap-2 text-[10px] text-white/61"><input type="checkbox" checked={contrast} onChange={e=>setContrast(e.target.checked)} className="accent-[#e8b760]"/>Enable high-contrast verification mode</label><div className="mt-3 grid gap-1 text-[10px] text-white/51"><p><Type size={12} className="mr-1 inline text-[#b9c7ff]"/>Focus-visible controls and keyboard palette</p><p><MoonStar size={12} className="mr-1 inline text-[#b9c7ff]"/>Reduced-motion compatibility in global styles</p><p><Globe2 size={12} className="mr-1 inline text-[#b9c7ff]"/>Semantic landmarks and responsive navigation</p></div></div><div className="rounded border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><MonitorSmartphone size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/76">Private mobile companion</p></div><div className="mt-3 grid grid-cols-2 gap-2 text-center text-[9px] text-white/53"><span className="rounded border border-white/8 p-2">MDM enrollment<br/><b className="text-[#f2cb82]">Required</b></span><span className="rounded border border-white/8 p-2">Device attestation<br/><b className="text-[#f2cb82]">Required</b></span><span className="rounded border border-white/8 p-2">Offline encrypted pack<br/><b className="text-[#f2cb82]">Scoped</b></span><span className="rounded border border-white/8 p-2">Remote revocation<br/><b className="text-[#f2cb82]">Required</b></span></div><p className="mt-3 flex gap-2 text-[10px] text-white/42"><ShieldCheck size={13} className="text-[#b9c7ff]"/>No public device registration, location tracking, image capture, or external synchronization is enabled.</p></div></div>
  </section>;
}
