import { BellRing, Cable, CheckCircle2, ClipboardCheck, Command, ExternalLink, FileKey2, Filter, KeyRound, Link2Off, MailCheck, ShieldCheck, UsersRound } from "lucide-react";
import { useMemo, useState } from "react";

type Tab = "integrations" | "automation" | "delivery" | "workbench";
const adapterCatalog = [
  { name: "CMDB / inventory", kind: "CMDB", auth: "OAuth service identity", scope: "Read-only approved assets", egress: "Tenant allow-list", owner: "Architecture", state: "Review required" },
  { name: "Cloud & identity", kind: "Cloud / IdP", auth: "Short-lived role", scope: "Approved accounts and metadata", egress: "Private endpoint", owner: "Cloud Security", state: "Review required" },
  { name: "Vulnerability & EDR", kind: "Assurance", auth: "Scoped API token", scope: "Finding metadata only", egress: "Regional relay", owner: "Detection Engineering", state: "Review required" },
  { name: "Ticketing & GRC", kind: "Workflow", auth: "OAuth delegated app", scope: "Engagement-linked cases", egress: "Tenant HTTPS", owner: "Risk Operations", state: "Review required" },
  { name: "GIS & facilities", kind: "Spatial", auth: "Read-only service account", scope: "Approved layers and plans", egress: "Network allow-list", owner: "Facilities Security", state: "Review required" },
  { name: "SIEM & webhooks", kind: "Observability", auth: "Signed webhook", scope: "Sanitized audit events", egress: "Signature + rate limit", owner: "Platform Security", state: "Review required" },
];
const automations = [
  ["SLA escalation", "Escalate a pending remediation review after the approved SLA window."],
  ["Approval chain", "Route report, exception, and connector decisions through an explicit reviewer chain."],
  ["Retention review", "Prompt an owner before evidence enters a scheduled deletion or legal-hold state."],
  ["Control review", "Stage periodic policy and compliance-evidence recertification work."],
  ["Notification preview", "Preview a redacted message, audience, channel, and quiet-hour behavior before delivery."],
] as const;
const shortcuts = ["G then A: open Atlas", "G then O: open Operations", "C: focus command palette", "F: open scoped filter", "? : shortcut reference"];

export default function IntegrationAutomationDeliveryHub() {
  const [tab, setTab] = useState<Tab>("integrations");
  const [reviewed, setReviewed] = useState<Record<string, boolean>>({});
  const [enabled, setEnabled] = useState<Record<string, boolean>>({});
  const [invite, setInvite] = useState("client-reviewer@customer.example");
  const [savedFilter, setSavedFilter] = useState("Priority evidence review");
  const reviewedCount = useMemo(() => Object.values(reviewed).filter(Boolean).length, [reviewed]);
  return <section className="mt-4 atlas-surface p-4"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-start"><div><p className="eyebrow">INTEGRATION, AUTOMATION & DELIVERY CONTROL PLANE</p><h3 className="mt-1 font-['Barlow_Condensed'] text-2xl font-semibold tracking-[.07em] text-white">PRIVATE OPERATING SYSTEM</h3><p className="mt-1 max-w-3xl text-xs leading-5 text-white/52">Prepare approved integration contracts, automation policies, customer delivery workflows, and analyst collaboration habits before activating a private tenant. This public workspace never connects, sends, schedules, or invites externally.</p></div><span className="atlas-status">All outbound actions locked</span></div>
    <div className="mt-4 flex gap-1 overflow-x-auto border-b border-white/8 pb-2">{(["integrations", "automation", "delivery", "workbench"] as Tab[]).map((item) => <button key={item} onClick={() => setTab(item)} className={`shrink-0 rounded px-3 py-1.5 text-[10px] uppercase tracking-[.13em] ${tab === item ? "bg-[#e8b760]/12 text-[#f2cb82]" : "text-white/46 hover:text-white/75"}`}>{item}</button>)}</div>
    {tab === "integrations" && <div className="mt-4"><div className="mb-3 flex items-center justify-between"><p className="text-xs text-white/58">{reviewedCount}/{adapterCatalog.length} adapter contracts prepared for private security review.</p><span className="text-[10px] text-[#f2cb82]">No credentials stored</span></div><div className="grid gap-2 xl:grid-cols-2">{adapterCatalog.map((adapter) => <label key={adapter.name} className={`flex gap-3 rounded-lg border p-3 ${reviewed[adapter.name] ? "border-[#83a77c]/30 bg-[#83a77c]/[.05]" : "border-white/8 bg-black/20"}`}><input type="checkbox" checked={Boolean(reviewed[adapter.name])} onChange={(event) => setReviewed((current) => ({ ...current, [adapter.name]: event.target.checked }))} className="mt-0.5 accent-[#e8b760]"/><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><p className="text-[11px] font-medium text-white/75">{adapter.name}</p><span className="text-[9px] text-[#f2cb82]">{adapter.state}</span></div><div className="mt-2 grid grid-cols-2 gap-1 text-[9px] text-white/45"><span>Auth: {adapter.auth}</span><span>Owner: {adapter.owner}</span><span>Scope: {adapter.scope}</span><span>Egress: {adapter.egress}</span></div><p className="mt-2 flex items-center gap-1 text-[9px] text-[#b9c7ff]"><Link2Off size={11}/> Connection disabled in public build</p></div></label>)}</div></div>}
    {tab === "automation" && <div className="mt-4 grid gap-4 xl:grid-cols-[1.05fr_.95fr]"><div className="grid gap-2">{automations.map(([name, detail]) => <label key={name} className={`flex gap-3 rounded-lg border p-3 ${enabled[name] ? "border-[#e8b760]/32 bg-[#e8b760]/[.05]" : "border-white/8 bg-black/20"}`}><input type="checkbox" checked={Boolean(enabled[name])} onChange={(event) => setEnabled((current) => ({ ...current, [name]: event.target.checked }))} className="mt-0.5 accent-[#e8b760]"/><div><p className="text-[11px] font-medium text-white/75">{name}</p><p className="mt-1 text-[10px] leading-4 text-white/48">{detail}</p></div></label>)}</div><div className="rounded-lg border border-[#e8b760]/18 bg-[#e8b760]/[.045] p-4"><div className="flex items-center gap-2"><BellRing size={16} className="text-[#f2cb82]"/><p className="text-sm font-semibold text-white/78">Automation preview</p></div><p className="mt-3 text-[11px] leading-5 text-white/56">Audience: <b className="text-white/75">Synthetic remediation owner</b><br/>Channel: <b className="text-white/75">Private notification policy</b><br/>Quiet hours: <b className="text-white/75">Respected</b><br/>Approval: <b className="text-white/75">Required before send</b></p><div className="mt-4 rounded border border-white/8 bg-black/20 p-3 text-[10px] text-white/49">“A synthetic remediation commitment reached its review window. This preview is not sent and does not schedule a future action.”</div></div></div>}
    {tab === "delivery" && <div className="mt-4 grid gap-4 xl:grid-cols-2"><div className="rounded-lg border border-white/8 bg-black/20 p-4"><div className="flex items-center gap-2"><MailCheck size={16} className="text-[#e8b760]"/><p className="text-sm font-semibold text-white/78">Client invitation lifecycle</p></div><input value={invite} onChange={(event) => setInvite(event.target.value)} className="mt-4 h-9 w-full rounded border border-white/10 bg-black/25 px-2 text-xs text-white"/><div className="mt-3 grid grid-cols-3 gap-2 text-center text-[9px]"><span className="rounded border border-white/8 p-2 text-white/46">Draft</span><span className="rounded border border-white/8 p-2 text-white/46">Approval required</span><span className="rounded border border-white/8 p-2 text-white/46">Expiring access</span></div><button disabled className="atlas-action mt-4 w-full justify-center text-xs opacity-50"><ExternalLink size={13}/> Send invite locked</button></div><div className="rounded-lg border border-white/8 bg-black/20 p-4"><div className="flex items-center gap-2"><FileKey2 size={16} className="text-[#e8b760]"/><p className="text-sm font-semibold text-white/78">Delivery checklist</p></div><div className="mt-3 grid gap-2 text-[10px] text-white/56">{["Brand profile and audience permission reviewed", "Evidence bundle redaction approved", "Exception expiry and attestation status confirmed", "Retest closure and acknowledgement staged"].map((item) => <p key={item} className="flex items-center gap-2 rounded border border-white/8 p-2"><CheckCircle2 size={13} className="text-[#b9c7ff]"/>{item}</p>)}</div></div></div>}
    {tab === "workbench" && <div className="mt-4 grid gap-4 xl:grid-cols-[.9fr_1.1fr]"><div className="rounded-lg border border-white/8 bg-black/20 p-4"><div className="flex items-center gap-2"><Filter size={16} className="text-[#e8b760]"/><p className="text-sm font-semibold text-white/78">Personal analyst workbench</p></div><input value={savedFilter} onChange={(event) => setSavedFilter(event.target.value)} className="mt-4 h-9 w-full rounded border border-white/10 bg-black/25 px-2 text-xs text-white"/><button className="atlas-action mt-3 text-xs"><ClipboardCheck size={13}/> Save synthetic filter</button><p className="mt-3 text-[10px] text-white/42">Work queue: 3 evidence checks · 2 pending approvals · 1 handoff brief</p></div><div className="rounded-lg border border-white/8 bg-black/20 p-4"><div className="flex items-center gap-2"><Command size={16} className="text-[#e8b760]"/><p className="text-sm font-semibold text-white/78">Command shortcuts & handoff</p></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{shortcuts.map((shortcut) => <p key={shortcut} className="rounded border border-white/8 px-2.5 py-2 text-[10px] text-white/56">{shortcut}</p>)}</div><p className="mt-3 flex items-center gap-2 text-[10px] text-white/42"><UsersRound size={13} className="text-[#b9c7ff]"/>Handoff brief should include authorization status, scope changes, decisions, evidence freshness, blockers, and the next accountable owner.</p></div></div>}
    <p className="mt-4 flex items-center gap-2 text-[10px] text-white/42"><ShieldCheck size={13} className="text-[#e8b760]"/>Private tenants should bind every enabled adapter and automation to an owner, approved scope, audit event, reversible configuration, and incident contact.</p>
  </section>;
}
