import { BadgeCheck, BookOpenCheck, CheckSquare, ClipboardList, Flag, History, Layers3, MapPinned, Palette, ShieldCheck, UsersRound } from "lucide-react";
import { useState } from "react";

type Tab = "delivery" | "collaboration" | "assurance" | "spatial" | "portfolio";

export default function OperationalDetailStudio() {
  const [tab, setTab] = useState<Tab>("delivery");
  const [theme, setTheme] = useState("Midnight Gold");
  const [acknowledged, setAcknowledged] = useState(false);
  const [evidenceReviewed, setEvidenceReviewed] = useState(false);
  const [closure, setClosure] = useState("Awaiting retest sign-off");
  const [preferences, setPreferences] = useState({ compact: false, conflict: true, bulk: false });
  const [hold, setHold] = useState("No active legal hold");
  const [floorVersion, setFloorVersion] = useState("v1.4 vs v1.3");
  const [rationale, setRationale] = useState("Prioritize evidence freshness and the highest supported service-impact reduction first.");
  const [manifestPrepared, setManifestPrepared] = useState(false);
  return <section className="mt-4 atlas-surface p-4"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-start"><div><p className="eyebrow">OPERATIONAL DETAIL STUDIO</p><h3 className="mt-1 font-['Barlow_Condensed'] text-2xl font-semibold tracking-[.07em] text-white">CLOSURE, ASSURANCE & DECISION CONTROLS</h3><p className="mt-1 max-w-3xl text-xs leading-5 text-white/52">Concrete public-demo models for the final operational details of a private tenant. Each control is local, synthetic, and outbound locked; the equivalent private workflow should persist state and append an audit event.</p></div><span className="atlas-status">Synthetic workflow models</span></div>
    <div className="mt-4 flex gap-1 overflow-x-auto border-b border-white/8 pb-2">{(["delivery", "collaboration", "assurance", "spatial", "portfolio"] as Tab[]).map((item) => <button key={item} onClick={() => setTab(item)} className={`shrink-0 rounded px-3 py-1.5 text-[10px] uppercase tracking-[.13em] ${tab === item ? "bg-[#e8b760]/12 text-[#f2cb82]" : "text-white/46 hover:text-white/75"}`}>{item}</button>)}</div>
    {tab === "delivery" && <div className="mt-4 grid gap-4 xl:grid-cols-3"><div className="rounded border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><Palette size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/75">Branded workspace theme</p></div><select value={theme} onChange={(event) => setTheme(event.target.value)} className="mt-3 h-9 w-full rounded border border-white/10 bg-black/25 px-2 text-xs text-white"><option>Midnight Gold</option><option>Client Navy</option><option>Restricted Neutral</option></select><p className="mt-2 text-[10px] text-white/43">Theme selection affects delivery presentation only; security labels and watermarks remain mandatory.</p></div><div className="rounded border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><CheckSquare size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/75">Acknowledgement & evidence review</p></div><label className="mt-3 flex gap-2 text-[10px] text-white/61"><input type="checkbox" checked={acknowledged} onChange={(e) => setAcknowledged(e.target.checked)} className="accent-[#e8b760]"/>Client acknowledgement staged</label><label className="mt-2 flex gap-2 text-[10px] text-white/61"><input type="checkbox" checked={evidenceReviewed} onChange={(e) => setEvidenceReviewed(e.target.checked)} className="accent-[#e8b760]"/>Audience evidence review staged</label><p className="mt-2 text-[9px] text-[#b9c7ff]">Expiry: 2026-10-01 · exception owner review required</p></div><div className="rounded border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><BadgeCheck size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/75">Retest closure certification</p></div><select value={closure} onChange={(e) => setClosure(e.target.value)} className="mt-3 h-9 w-full rounded border border-white/10 bg-black/25 px-2 text-xs text-white"><option>Awaiting retest sign-off</option><option>Evidence review complete</option><option>Closure certification ready</option><option>Closed with accepted exception</option></select><p className="mt-2 text-[10px] text-white/43">Private closure must retain attestor, evidence hash, exception expiry, and immutable decision event.</p></div></div>}
    {tab === "collaboration" && <div className="mt-4 grid gap-4 xl:grid-cols-[.9fr_1.1fr]"><div className="rounded border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><UsersRound size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/75">Analyst preferences & bulk review plan</p></div><div className="mt-3 grid gap-2">{[["compact", "Compact workspace density"],["conflict", "Flag conflicting evidence and ownership"],["bulk", "Stage bulk review plan for selected evidence records"]].map(([key,label]) => <label key={key} className="flex gap-2 rounded border border-white/8 p-2 text-[10px] text-white/61"><input type="checkbox" checked={preferences[key as keyof typeof preferences]} onChange={(e) => setPreferences((current) => ({ ...current, [key]: e.target.checked }))} className="accent-[#e8b760]"/>{label}</label>)}</div><p className="mt-3 text-[10px] text-white/43">Private tenant preference storage should be user-scoped, encrypted where necessary, and auditable when it alters review scope.</p></div><div className="rounded border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><History size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/75">Decision timeline & handoff brief</p></div><div className="mt-3 grid gap-2 text-[10px]">{[["09:15", "Scope reviewer confirmed declared synthetic zone"],["09:42", "Evidence conflict flagged for ownership check"],["10:05", "Bulk review plan staged for three validation records"],["Next", "Handoff: analyst → delivery reviewer with evidence freshness note"]].map(([time,detail]) => <div key={time} className="flex gap-3 rounded border border-white/8 p-2"><span className="text-[#f2cb82]">{time}</span><span className="text-white/57">{detail}</span></div>)}</div></div></div>}
    {tab === "assurance" && <div className="mt-4 grid gap-4 xl:grid-cols-3"><div className="rounded border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><BookOpenCheck size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/75">Exception & legal-hold register</p></div><select value={hold} onChange={(e) => setHold(e.target.value)} className="mt-3 h-9 w-full rounded border border-white/10 bg-black/25 px-2 text-xs text-white"><option>No active legal hold</option><option>Legal hold review requested</option><option>Legal hold active</option></select><p className="mt-2 text-[10px] text-white/43">Exception EX-SYN-01 expires 2026-10-01; owner and reviewer attestation required.</p></div><div className="rounded border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><ShieldCheck size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/75">Residency & privacy matrix</p></div><div className="mt-3 grid gap-1 text-[10px] text-white/57"><p>Workspace metadata · approved private region · retention profile</p><p>Evidence objects · scoped object storage · custody logging</p><p>Coordinates · precision profile · export redaction</p><p>Connector records · tenant allow-list · revocation path</p></div></div><div className="rounded border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><ClipboardList size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/75">Audit pack builder</p></div><div className="mt-3 grid gap-1 text-[10px] text-white/57"><p>✓ Authorization and scope snapshot</p><p>✓ Control-owner and attestation register</p><p>✓ Evidence references and export approvals</p><p>✓ Exceptions, legal hold, and closure ledger</p></div><button onClick={() => setManifestPrepared(true)} className="atlas-action mt-3 text-xs">{manifestPrepared ? "Synthetic manifest prepared" : "Prepare synthetic pack manifest"}</button>{manifestPrepared && <p role="status" className="mt-2 text-[9px] text-[#bde0b5]">Manifest staged in this browser session; no artifact was exported or delivered.</p>}</div></div>}
    {tab === "spatial" && <div className="mt-4 grid gap-4 xl:grid-cols-[1fr_1fr]"><div className="rounded border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><Layers3 size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/75">Floor-plan and imagery change review</p></div><select value={floorVersion} onChange={(e) => setFloorVersion(e.target.value)} className="mt-3 h-9 w-full rounded border border-white/10 bg-black/25 px-2 text-xs text-white"><option>v1.4 vs v1.3</option><option>v1.3 vs v1.2</option><option>Approved baseline only</option></select><p className="mt-2 text-[10px] text-white/48">Change markers: 2 access-transition labels updated; 1 zone stewardship annotation pending review. Imagery plan: scheduled comparison only, no remote collection.</p></div><div className="rounded border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><MapPinned size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/75">Observation quality & zone allocation</p></div><div className="mt-3 grid grid-cols-3 gap-2 text-center text-[9px]"><span className="rounded border border-white/8 p-2 text-white/57">Northstar<br/><b className="text-[#f2cb82]">2 reviewers</b></span><span className="rounded border border-white/8 p-2 text-white/57">Aurora<br/><b className="text-[#f2cb82]">1 reviewer</b></span><span className="rounded border border-white/8 p-2 text-white/57">Solstice<br/><b className="text-[#f2cb82]">1 reviewer</b></span></div><p className="mt-2 text-[10px] text-white/43">Observation quality: source provenance, timestamp, precision, reviewer, and scope fit are required before use.</p></div></div>}
    {tab === "portfolio" && <div className="mt-4 grid gap-4 xl:grid-cols-[.85fr_1.15fr]"><div className="rounded border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><Flag size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/75">Portfolio priority rationale</p></div><textarea value={rationale} onChange={(e) => setRationale(e.target.value)} className="mt-3 min-h-24 w-full rounded border border-white/10 bg-black/25 p-2 text-xs text-white"/><p className="mt-2 text-[10px] text-white/43">A private decision must cite data age, confidence, scope, service owner, risk factors, assumptions, and accountable approver.</p></div><div className="rounded border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><ShieldCheck size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/75">Synthetic forecast range</p></div><div className="mt-3 grid grid-cols-3 gap-2">{[["Service impact", "Medium → Low", "With edge remediation"],["Risk exposure", "−12% to −34%", "Scenario range"],["Effort", "9–18 units", "Planning index"]].map(([label,value,detail]) => <div key={label} className="rounded border border-white/8 p-2"><p className="text-[9px] uppercase tracking-[.1em] text-white/35">{label}</p><p className="mt-1 text-[11px] text-[#f2cb82]">{value}</p><p className="mt-1 text-[9px] text-white/42">{detail}</p></div>)}</div><p className="mt-3 text-[10px] leading-4 text-white/44">Forecasting remains illustrative. It is a decision-support comparison, not a financial forecast, guarantee, or automatic remediation recommendation.</p></div></div>}
  </section>;
}
