import { BadgeCheck, BriefcaseBusiness, ClipboardList, FileCheck2, Handshake, Scale, ShieldCheck, UsersRound } from "lucide-react";
import { useState } from "react";

type Tab = "operations" | "delivery" | "assurance" | "commercial";
export default function OperationalReadinessPack() {
  const [tab,setTab]=useState<Tab>("operations"); const [retrospective,setRetrospective]=useState("Capture scope variance, evidence freshness, decision delays, and improvement owners."); const [stagedChecklist,setStagedChecklist]=useState<string | null>(null);
  return <section className="mt-4 atlas-surface p-4"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-start"><div><p className="eyebrow">PUBLIC-SAFE OPERATING READINESS PACK</p><h3 className="mt-1 font-['Barlow_Condensed'] text-2xl font-semibold tracking-[.07em] text-white">SERVICE, ASSURANCE & CUSTOMER OPERATIONS</h3><p className="mt-1 max-w-3xl text-xs leading-5 text-white/52">Model the operational fabric of a private assessment program without contacting stakeholders, sending delivery, accepting customer data, or claiming live contractual status.</p></div><span className="atlas-status">Readiness artifacts only</span></div>
    <div className="mt-4 flex gap-1 border-b border-white/8 pb-2">{(["operations","delivery","assurance","commercial"] as Tab[]).map(item=><button key={item} onClick={()=>setTab(item)} className={`rounded px-3 py-1.5 text-[10px] uppercase tracking-[.13em] ${tab===item?"bg-[#e8b760]/12 text-[#f2cb82]":"text-white/46"}`}>{item}</button>)}</div>
    {tab==="operations" && <div className="mt-4 grid gap-4 xl:grid-cols-[1.1fr_.9fr]"><div className="rounded border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><UsersRound size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/76">Stakeholder RACI & escalation matrix</p></div><div className="mt-3 overflow-x-auto"><table className="atlas-table text-[10px]"><thead><tr><th>Decision</th><th>Responsible</th><th>Accountable</th><th>Review SLA</th></tr></thead><tbody>{[["Scope change","Assessment lead","Engagement manager","1 business day"],["Evidence classification","Evidence custodian","Security owner","4 hours"],["Client delivery","Delivery reviewer","Account owner","2 business days"],["Exception closure","Control owner","Risk committee","Before expiry"]].map(row=><tr key={row[0]}>{row.map(cell=><td key={cell} className="text-white/57">{cell}</td>)}</tr>)}</tbody></table></div></div><div className="rounded border border-white/8 bg-black/20 p-3"><p className="text-xs font-semibold text-white/76">Capacity & decision log</p><div className="mt-3 grid gap-2 text-[10px] text-white/54"><p className="rounded border border-white/8 p-2">Capacity: 4 synthetic reviewers · 2 campaigns · no external assignment</p><p className="rounded border border-white/8 p-2">Escalation: review SLA → accountable owner → risk committee</p><textarea value={retrospective} onChange={e=>setRetrospective(e.target.value)} className="min-h-20 rounded border border-white/10 bg-black/25 p-2 text-xs text-white"/></div></div></div>}
    {tab==="delivery" && <div className="mt-4 grid gap-4 xl:grid-cols-3">{[["Evidence preview","Classification, provenance, derivative, redaction zones, custody and reviewer are staged before private delivery."],["Report signature readiness","Private delivery should bind approved signer, audience, watermark, expiry, acknowledgement, and immutable manifest."],["Retest closure","Closure checklist includes evidence review, remediation attestation, exception expiry, reviewer, and client acknowledgement."]].map(([title,detail])=><div key={title} className="rounded border border-white/8 bg-black/20 p-3"><FileCheck2 size={16} className="text-[#e8b760]"/><p className="mt-2 text-xs font-semibold text-white/76">{title}</p><p className="mt-2 text-[10px] leading-5 text-white/50">{detail}</p><button onClick={()=>setStagedChecklist(title)} className="atlas-action mt-3 text-xs">{stagedChecklist===title?"Checklist staged":"Stage synthetic checklist"}</button>{stagedChecklist===title&&<p role="status" className="mt-2 text-[10px] text-[#bde0b5]">Staged locally for planning; no report, delivery, or notification was sent.</p>}</div>)}</div>}
    {tab==="assurance" && <div className="mt-4 grid gap-4 xl:grid-cols-2"><div className="rounded border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><ShieldCheck size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/76">Framework, exception & policy register</p></div><div className="mt-3 grid gap-2 text-[10px] text-white/55">{["Framework catalog: customer-selected mappings only","Evidence request register: owner, due date, classification","Exception expiry: owner attestation before expiration","Policy attestation: approved version, scope, reviewer"].map(item=><p key={item} className="rounded border border-white/8 p-2">{item}</p>)}</div></div><div className="rounded border border-white/8 bg-black/20 p-3"><div className="flex items-center gap-2"><Handshake size={15} className="text-[#e8b760]"/><p className="text-xs font-semibold text-white/76">Supplier assurance & audit pack</p></div><div className="mt-3 grid gap-2 text-[10px] text-white/55">{["Contract-control checklist and renewal review","Provider concentration, contingency, and control evidence","Audit-pack index: scope, decisions, evidence, exceptions","No claim of supplier certification in public mode"].map(item=><p key={item} className="rounded border border-white/8 p-2">{item}</p>)}</div></div></div>}
    {tab==="commercial" && <div className="mt-4 grid gap-4 xl:grid-cols-3">{[["Packaging & entitlement","Starter / Professional / Enterprise capability matrix, named tenant features, and internal entitlement review."],["Procurement & privacy","Security-questionnaire response library, privacy notice checklist, DPA readiness, and data-processing review."],["Support & success","Support severity matrix, escalation ownership, onboarding plan, adoption health score, and renewal signals."]].map(([title,detail])=><div key={title} className="rounded border border-white/8 bg-black/20 p-3"><BriefcaseBusiness size={16} className="text-[#e8b760]"/><p className="mt-2 text-xs font-semibold text-white/76">{title}</p><p className="mt-2 text-[10px] leading-5 text-white/50">{detail}</p><p className="mt-3 flex items-center gap-2 text-[10px] text-[#b9c7ff]"><Scale size={12}/> Public model only; no billing or contracts activated.</p></div>)}</div>}
    <p className="mt-4 flex gap-2 text-[10px] text-white/42"><BadgeCheck size={13} className="text-[#e8b760]"/><ClipboardList size={13} className="text-[#e8b760]"/>Private deployment must make these records tenant-bound, role-gated, auditable, and governed by approved legal, security, and procurement processes.</p>
  </section>;
}
