import { BadgeCheck, CloudCog, DatabaseZap, FileKey2, LockKeyhole, Network, ShieldAlert, UserRoundCheck } from "lucide-react";

const readinessChecks = [
  { label: "Signed engagement authorization", state: "Required", detail: "Document explicit scope, duration, systems, sites, and exclusions before accepting customer records.", complete: false },
  { label: "Private identity boundary", state: "Required", detail: "Use organization SSO, least-privilege roles, invitation approval, and revocation controls.", complete: false },
  { label: "Encrypted private evidence storage", state: "Required", detail: "Use a private bucket, signed retrieval, malware scanning, lifecycle policies, and immutable integrity metadata.", complete: false },
  { label: "Approved data-processing profile", state: "Required", detail: "Set data residency, retention, legal hold, redaction, and export approvals.", complete: false },
  { label: "Connector security review", state: "Required", detail: "Approve each organization-owned adapter, service account, egress path, and audit policy.", complete: false },
  { label: "Public demo isolation", state: "Active", detail: "This build intentionally contains synthetic records only and cannot promote external target data.", complete: true },
];

const adapters = [
  { icon: DatabaseZap, label: "CMDB / asset inventory", purpose: "Asset owner, business service, lifecycle, and criticality context" },
  { icon: CloudCog, label: "Cloud posture & identity", purpose: "Authorized account, resource, exposure, and identity-risk metadata" },
  { icon: ShieldAlert, label: "Vulnerability & EDR evidence", purpose: "Approved findings, evidence references, validation timestamps, and remediation state" },
  { icon: Network, label: "Network & external surface", purpose: "Customer-approved asset observations and scope-bound topology metadata" },
  { icon: UserRoundCheck, label: "Ticketing / GRC", purpose: "Ownership, risk acceptance, remediation commitments, and review workflow" },
  { icon: FileKey2, label: "GIS / facilities context", purpose: "Organization-owned sites, zones, floor plans, and field-assessment boundaries" },
];

export default function PrivateDeploymentReadiness() {
  const completed = readinessChecks.filter((check) => check.complete).length;
  const score = Math.round((completed / readinessChecks.length) * 100);
  return <section className="mt-4 atlas-surface overflow-hidden"><div className="border-b border-white/10 bg-[linear-gradient(110deg,rgba(232,183,96,.09),transparent_46%,rgba(135,191,255,.07))] p-4"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-start"><div><p className="eyebrow">PUBLIC DEMO / PRIVATE AUTHORIZED DEPLOYMENT CONTROL PLANE</p><h3 className="mt-1 font-['Barlow_Condensed'] text-2xl font-semibold tracking-[.07em] text-white">PRIVATE DATA READINESS</h3><p className="mt-1 max-w-3xl text-xs leading-5 text-white/55">The public workspace remains synthetic. This control plane shows exactly what must be established before a private organization deployment may ingest consented, organization-owned assessment data.</p></div><div className="rounded-lg border border-[#e8b760]/25 bg-black/25 px-3 py-2 text-right"><p className="text-[9px] uppercase tracking-[.14em] text-white/40">Private readiness</p><p className="mt-1 text-xl font-semibold text-[#f2cb82]">{score}%</p><p className="text-[10px] text-white/45">{completed} / {readinessChecks.length} controls configured</p></div></div></div>
    <div className="grid gap-4 p-4 xl:grid-cols-[1.08fr_.92fr]"><div><p className="eyebrow">DEPLOYMENT GATES</p><div className="mt-3 grid gap-2">{readinessChecks.map((check) => <div key={check.label} className="flex items-start gap-3 rounded-lg border border-white/8 bg-black/20 p-3"><div className={`mt-0.5 rounded p-1 ${check.complete ? "bg-[#83a77c]/15 text-[#bde0b5]" : "bg-[#e8b760]/10 text-[#f2cb82]"}`}><BadgeCheck size={14}/></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="text-xs font-medium text-white/78">{check.label}</p><span className={`text-[9px] uppercase tracking-[.12em] ${check.complete ? "text-[#bde0b5]" : "text-[#f2cb82]"}`}>{check.state}</span></div><p className="mt-1 text-[10px] leading-4 text-white/47">{check.detail}</p></div></div>)}</div></div><div><p className="eyebrow">APPROVED PRIVATE DATA ADAPTERS</p><p className="mt-1 text-[11px] leading-5 text-white/48">Adapters are intentionally unconfigured in this public build. Private deployment requires a connector review, a scoped service identity, audit coverage, and an approved data-processing basis.</p><div className="mt-3 grid gap-2">{adapters.map((adapter) => <div key={adapter.label} className="flex items-start gap-3 rounded-lg border border-white/8 bg-black/20 p-3"><adapter.icon size={15} className="mt-0.5 text-[#b9c7ff]"/><div className="min-w-0"><p className="text-xs font-medium text-white/75">{adapter.label}</p><p className="mt-1 text-[10px] leading-4 text-white/45">{adapter.purpose}</p><span className="mt-2 inline-block rounded border border-white/10 px-1.5 py-0.5 text-[8px] uppercase tracking-[.12em] text-white/38">Not connected in public demo</span></div></div>)}</div></div></div>
    <div className="flex flex-col gap-2 border-t border-white/10 bg-black/25 px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><p className="flex items-center gap-2 text-[11px] text-white/52"><LockKeyhole size={13} className="text-[#e8b760]"/>A production onboarding path must fail closed: no authorization, no scope approval, no private data intake.</p><button disabled className="atlas-action text-xs opacity-50"><LockKeyhole size={13}/> Private onboarding locked in public build</button></div></section>;
}
