import { Database, FileCheck2, KeyRound, LockKeyhole, Network, ScanSearch, ShieldCheck, UserCog } from "lucide-react";
import { useMemo, useState } from "react";

const connectors = [
  { id: "cmdb", label: "CMDB / asset inventory", icon: Database, data: "Asset, owner, business service, lifecycle, classification", scope: "Only approved organizations and engagement assets", retention: "Engagement + 90 day review", owner: "Enterprise Architecture" },
  { id: "cloud", label: "Cloud & identity posture", icon: UserCog, data: "Authorized account/resource metadata and identity-risk context", scope: "Approved cloud accounts and read-only fields", retention: "Engagement + approved policy", owner: "Cloud Security" },
  { id: "vuln", label: "Vulnerability / EDR evidence", icon: ScanSearch, data: "Finding metadata, evidence references, validation time, remediation state", scope: "In-scope assets; no raw telemetry by default", retention: "Evidence lifecycle policy", owner: "Detection Engineering" },
  { id: "ticket", label: "Ticketing / GRC", icon: FileCheck2, data: "Ownership, commitments, exceptions, risk acceptance, approvals", scope: "Engagement-linked records only", retention: "Case closure + audit policy", owner: "Risk Operations" },
  { id: "gis", label: "GIS / facilities context", icon: Network, data: "Sites, work zones, approved floor plans, access-transition metadata", scope: "Approved facilities with privacy profile", retention: "Site review window", owner: "Facilities Security" },
] as const;

export default function PrivateDataOnboardingInventory() {
  const [selectedId, setSelectedId] = useState<(typeof connectors)[number]["id"]>("cmdb");
  const [checks, setChecks] = useState({ authorization: false, identity: false, minimization: false, retention: false, audit: false });
  const selected = connectors.find((connector) => connector.id === selectedId) ?? connectors[0];
  const Icon = selected.icon;
  const completed = Object.values(checks).filter(Boolean).length;
  const ready = completed === 5;
  const gates = useMemo(() => [
    ["authorization", "Signed scope & data-processing approval"],
    ["identity", "Scoped service identity and least privilege"],
    ["minimization", "Field-level data-minimization profile"],
    ["retention", "Retention, legal-hold, and deletion policy"],
    ["audit", "Connector audit, owner, and revocation plan"],
  ] as const, []);
  return <section className="mt-4 atlas-surface p-4"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-start"><div><p className="eyebrow">PRIVATE DATA ONBOARDING / CONNECTOR GOVERNANCE</p><h3 className="mt-1 font-['Barlow_Condensed'] text-2xl font-semibold tracking-[.07em] text-white">APPROVAL-FIRST ADAPTER INVENTORY</h3><p className="mt-1 max-w-3xl text-xs leading-5 text-white/52">Plan the minimum approved data adapters for a private deployment. No adapter is connected in this public build; this interface prevents “connect first, govern later” behavior.</p></div><span className={`atlas-status ${ready ? "text-[#bde0b5]" : ""}`}>{ready ? "Ready for private review" : `${completed}/5 approval gates`}</span></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[.72fr_1.28fr]"><div className="grid gap-2">{connectors.map((connector) => { const ConnectorIcon = connector.icon; const selectedConnector = connector.id === selected.id; return <button key={connector.id} onClick={() => setSelectedId(connector.id)} className={`flex items-start gap-3 rounded-lg border p-3 text-left ${selectedConnector ? "border-[#e8b760]/45 bg-[#e8b760]/[.07]" : "border-white/8 bg-black/20 hover:border-white/20"}`}><ConnectorIcon size={16} className={selectedConnector ? "text-[#f2cb82]" : "text-[#b9c7ff]"}/><div><p className="text-[11px] font-medium text-white/74">{connector.label}</p><p className="mt-1 text-[9px] text-white/40">Owner: {connector.owner}</p></div></button>})}</div>
      <div className="rounded-lg border border-white/8 bg-black/20 p-4"><div className="flex items-start gap-3"><div className="rounded-lg bg-[#e8b760]/10 p-2 text-[#f2cb82]"><Icon size={19}/></div><div><p className="text-sm font-semibold text-white/80">{selected.label}</p><p className="mt-1 text-[11px] leading-5 text-white/54">Public status: **not connected**. A private tenant may only onboard this adapter after every gate below is independently approved.</p></div></div><div className="mt-4 grid gap-2 sm:grid-cols-2"><div className="rounded border border-white/8 p-2.5"><p className="text-[9px] uppercase tracking-[.12em] text-white/35">Minimum data profile</p><p className="mt-1 text-[11px] leading-4 text-white/64">{selected.data}</p></div><div className="rounded border border-white/8 p-2.5"><p className="text-[9px] uppercase tracking-[.12em] text-white/35">Scope & lifecycle</p><p className="mt-1 text-[11px] leading-4 text-white/64">{selected.scope}</p><p className="mt-1 text-[10px] text-[#b9c7ff]">{selected.retention}</p></div></div><div className="mt-4"><p className="text-[9px] uppercase tracking-[.14em] text-white/38">Private onboarding gates</p><div className="mt-2 grid gap-1.5">{gates.map(([key, label]) => <label key={key} className="flex cursor-pointer items-center gap-2 rounded border border-white/8 px-2.5 py-2 text-[10px] text-white/61"><input type="checkbox" checked={checks[key]} onChange={(event) => setChecks((current) => ({ ...current, [key]: event.target.checked }))} className="accent-[#e8b760]"/>{label}</label>)}</div></div><div className="mt-4 flex items-center justify-between gap-3 rounded border border-[#e8b760]/18 bg-[#e8b760]/[.045] px-3 py-2"><p className="flex items-center gap-2 text-[10px] leading-4 text-white/57"><ShieldCheck size={14} className="shrink-0 text-[#f2cb82]"/>{ready ? "All planning gates are selected; private tenant review is still required before any connection is enabled." : "This public demonstration cannot create credentials, request access, or initiate data transfer."}</p><button disabled className="atlas-action shrink-0 text-xs opacity-50"><LockKeyhole size={13}/> Connect locked</button></div></div></div>
    <p className="mt-3 flex items-center gap-2 text-[10px] text-white/42"><KeyRound size={13} className="text-[#b9c7ff]"/>Recommended private implementation: short-lived scoped credentials, encrypted secrets manager, connector allow-list, egress controls, audit export, and immediate revocation capability.</p>
  </section>;
}
