import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Archive, CheckCircle2, ClipboardCheck, FileText, FileUp, Layers3, ShieldCheck, UsersRound } from "lucide-react";
import { useState, type ChangeEvent } from "react";

const demoTasks = [
  { title: "Review edge exposure variance", priority: "critical", status: "in-progress", owner: "Platform Engineering" },
  { title: "Approve geographic evidence register", priority: "high", status: "review", owner: "Lead Analyst" },
  { title: "Schedule synthetic retest window", priority: "medium", status: "open", owner: "Assessment Manager" },
];

export default function ProductionOperations() {
  const { user } = useAuth();
  const snapshot = trpc.workspace.operationsSnapshot.useQuery({ engagementId: 1 }, { enabled: Boolean(user) });
  const privateRecords = trpc.workspace.persistentRecords.useQuery(undefined, { enabled: Boolean(user) });
  const utils = trpc.useUtils();
  const createTask = trpc.workspace.createTask.useMutation({ onSuccess: () => utils.workspace.operationsSnapshot.invalidate({ engagementId: 1 }) });
  const createArtifact = trpc.workspace.createGeospatialArtifact.useMutation({ onSuccess: () => utils.workspace.operationsSnapshot.invalidate({ engagementId: 1 }) });
  const createReport = trpc.workspace.createReportDelivery.useMutation({ onSuccess: () => utils.workspace.operationsSnapshot.invalidate({ engagementId: 1 }) });
  const uploadEvidence = trpc.workspace.uploadEvidence.useMutation();
  const [message, setMessage] = useState("");
  const [evidenceName, setEvidenceName] = useState("");
  const [findingLink, setFindingLink] = useState("");
  const taskRows = snapshot.data?.tasks.length ? snapshot.data.tasks.map((task) => ({ title: task.title, priority: task.priority, status: task.taskStatus, owner: task.assignedUserId ? `User #${task.assignedUserId}` : "Unassigned" })) : demoTasks;
  const persist = (kind: "task" | "artifact" | "report") => {
    if (!user) { setMessage("Sign in to persist operations. The public demonstration remains synthetic and read-only."); return; }
    if (kind === "task") createTask.mutate({ engagementId: 1, title: "Review synthetic geographic exposure update", priority: "high" }, { onSuccess: () => setMessage("Remediation task persisted and audit event appended.") });
    if (kind === "artifact") createArtifact.mutate({ engagementId: 1, title: "Synthetic AOI review layer", artifactType: "aoi", coordinatePrecision: "synthetic", metadataJson: { source: "Aegis Atlas operations center", synthetic: true } }, { onSuccess: () => setMessage("Geospatial artifact staged for analyst review.") });
    if (kind === "report") createReport.mutate({ engagementId: 1, reportType: "geographic", redactionProfile: "synthetic-demo" }, { onSuccess: () => setMessage("Geographic report delivery entered the governed draft queue.") });
  };
  const pending = createTask.isPending || createArtifact.isPending || createReport.isPending;
  const onEvidenceSelected = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;
    if (!user) { setMessage("Sign in to upload evidence. The public demonstration intentionally does not accept artifacts."); return; }
    if (file.size > 3_000_000) { setMessage("Evidence intake is limited to 3 MB per artifact in this deployment."); return; }
    setEvidenceName(file.name);
    const reader = new FileReader();
    reader.onload = () => {
      const dataUrl = String(reader.result ?? "");
      const base64 = dataUrl.includes(",") ? dataUrl.split(",")[1] : "";
      if (!base64) { setMessage("The selected artifact could not be encoded for secure intake."); return; }
      uploadEvidence.mutate({ engagementId: 1, fileName: file.name, mediaType: file.type || "application/octet-stream", base64, classification: "synthetic", findingId: findingLink ? Number(findingLink) : undefined }, { onSuccess: (result) => setMessage(`Evidence stored securely: ${result.originalName} · SHA-256 ${result.sha256.slice(0, 12)}…`) , onError: () => setMessage("Evidence intake failed. No metadata-only custody record was created.") });
    };
    reader.readAsDataURL(file);
  };
  return <>
    <div className="mb-5 flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><p className="eyebrow">PRODUCTION OPERATIONS / ENGAGEMENT DELIVERY</p><h2 className="atlas-heading mt-1">ENGAGEMENT OPERATIONS CENTER</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-white/52">A business-ready command layer for controlled work intake, collaboration, review gates, accountable reporting, and bounded client delivery. Public views use synthetic metrics; authenticated actions persist only metadata and audit history.</p></div><div className="atlas-status">{user ? "Authenticated workspace" : "Synthetic demonstration"}</div></div>
    {message && <div className="mb-4 rounded-lg border border-[#e8b760]/25 bg-[#e8b760]/[.06] px-3 py-2 text-xs text-[#f2cb82]" aria-live="polite">{message}</div>}
    <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Metric icon={ShieldCheck} label="Authorization" value="ACTIVE" detail="Scope policy enforced" tone="gold"/><Metric icon={UsersRound} label="Team readiness" value="4 / 4" detail="Synthetic roles assigned" tone="blue"/><Metric icon={ClipboardCheck} label="Remediation flow" value="03" detail="Open decision tasks" tone="gold"/><Metric icon={FileText} label="Client delivery" value="REVIEW" detail="One governed draft" tone="red"/></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.25fr_.75fr]"><section className="atlas-surface overflow-hidden"><div className="flex items-center justify-between border-b border-white/10 px-4 py-3"><div><p className="eyebrow">REMEDIATION & REVIEW QUEUE</p><p className="mt-1 text-xs text-white/48">Tasks are tied to engagement state and can be audited in private deployments.</p></div><button disabled={pending} onClick={() => persist("task")} className="atlas-action text-xs disabled:opacity-50"><ClipboardCheck size={13}/> Create task</button></div><div className="divide-y divide-white/8">{taskRows.map((task, index) => <div key={`${task.title}-${index}`} className="flex items-center justify-between gap-3 px-4 py-3"><div><p className="text-sm font-medium text-white/84">{task.title}</p><p className="mt-1 text-[10px] text-white/42">Owner · {task.owner} · evidence-backed change control</p></div><div className="flex gap-2"><span className={`atlas-status ${task.priority === "critical" ? "border-[#ee7664]/30 text-[#ffab9d]" : ""}`}>{task.priority}</span><span className="atlas-status">{task.status}</span></div></div>)}</div></section><section className="atlas-surface p-4"><p className="eyebrow">DELIVERY GOVERNANCE</p><div className="mt-4 space-y-3"><GovernanceStep n="01" title="Scope & geofence approved" detail="Out-of-scope records quarantine before analyst use."/><GovernanceStep n="02" title="Evidence custody reviewed" detail="Object storage is authoritative; database holds references only."/><GovernanceStep n="03" title="Report approval gate" detail="Redaction profile and reviewer approval precede sharing."/></div></section></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-3"><ActionCard icon={Layers3} title="Governed GIS artifact" detail="Stage a synthetic AOI, GeoJSON, floor-plan, or STAC metadata record for review." action="Stage layer" onClick={() => persist("artifact")} pending={pending}/><ActionCard icon={FileText} title="Client delivery draft" detail="Create a redaction-aware geographic report-delivery record with approval state." action="Create delivery" onClick={() => persist("report")} pending={pending}/><ActionCard icon={Archive} title="Evidence lifecycle" detail="Classify, retain, link, and audit evidence references without placing bytes in the database." action="View custody model" onClick={() => setMessage("Evidence custody uses immutable reference metadata, SHA-256, classification, provenance, retention state, and analyst review.")} pending={false}/></div>
    <section className="mt-4 atlas-surface p-4"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><p className="eyebrow">SECURE EVIDENCE INTAKE</p><p className="mt-2 max-w-2xl text-xs leading-5 text-white/55">Selected bytes are sent only to secured object storage. The workspace database receives the object reference, media type, byte size, SHA-256 integrity hash, classification, provenance, retention state, custody event, and audit event—never the file bytes.</p></div><label className={`atlas-action atlas-action-primary cursor-pointer ${uploadEvidence.isPending ? "pointer-events-none opacity-50" : ""}`}><FileUp size={15}/>{uploadEvidence.isPending ? "Storing artifact" : "Select evidence"}<input className="sr-only" type="file" accept="image/*,.txt,.json,.geojson,.csv,.pdf" onChange={onEvidenceSelected}/></label></div><div className="mt-3 flex flex-wrap items-center gap-2 text-[10px] text-white/42"><select value={findingLink} onChange={(event) => setFindingLink(event.target.value)} className="h-7 max-w-72 rounded border border-white/10 bg-black/20 px-2 text-[10px] text-white/65"><option value="">Unlinked intake artifact</option>{privateRecords.data?.findings.map((finding) => <option key={finding.id} value={finding.id}>{finding.stableId} · {finding.title}</option>)}</select><span className="rounded border border-white/10 px-2 py-1">Classification · synthetic</span><span className="rounded border border-white/10 px-2 py-1">Retention · active</span><span className="rounded border border-white/10 px-2 py-1">Size limit · 3 MB</span><span className="rounded border border-white/10 px-2 py-1">Malware scan · external review pending</span>{evidenceName && <span className="rounded border border-[#e8b760]/25 px-2 py-1 text-[#f0c678]">Selected · {evidenceName}</span>}</div></section>
    <div className="mt-4 grid gap-4 xl:grid-cols-[.8fr_1.2fr]"><section className="atlas-surface p-4"><p className="eyebrow">BUSINESS MODEL / PRODUCT PACKAGING</p><div className="mt-4 space-y-3"><Package label="Assessment workspace" value="Per-engagement" detail="Authorized scope, map, evidence, and report workflow."/><Package label="Operations portfolio" value="Per-team" detail="Engagement health, task throughput, remediation and delivery oversight."/><Package label="Enterprise governance" value="Annual" detail="Private deployment, SSO/role controls, retention, integrations, and audit exports."/></div></section><section className="atlas-surface p-4"><p className="eyebrow">BUYER & OUTCOME SIGNALS</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{[["CISO / security leader","Exposure concentration and business-ready reporting"],["Consultancy manager","Repeatable, auditable client delivery"],["Red-team lead","Scope safety, evidence traceability, and coordination"],["Infrastructure owner","Geographic dependency and remediation context"]].map(([persona, outcome]) => <div key={persona} className="rounded-lg border border-white/8 bg-black/20 p-3"><p className="text-xs font-semibold text-white/82">{persona}</p><p className="mt-2 text-[11px] leading-5 text-white/48">{outcome}</p></div>)}</div></section></div>
  </>;
}

function Metric({ icon: Icon, label, value, detail, tone }: { icon: typeof ShieldCheck; label: string; value: string; detail: string; tone: "gold" | "blue" | "red" }) { const cls = tone === "red" ? "text-[#ef796a]" : tone === "blue" ? "text-[#aabfff]" : "text-[#e8b760]"; return <div className="atlas-surface flex items-center gap-3 p-3.5"><div className={`flex h-9 w-9 items-center justify-center rounded-lg bg-white/[.035] ${cls}`}><Icon size={17}/></div><div><p className="text-[10px] uppercase tracking-[.15em] text-white/38">{label}</p><p className="mt-0.5 text-lg font-semibold text-white">{value}</p><p className="text-[10px] text-white/42">{detail}</p></div></div>; }
function GovernanceStep({ n, title, detail }: { n: string; title: string; detail: string }) { return <div className="flex gap-3"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full border border-[#e8b760]/35 text-[10px] font-semibold text-[#f2cb82]">{n}</span><div><p className="text-xs font-semibold text-white/78">{title}</p><p className="mt-1 text-[11px] leading-5 text-white/48">{detail}</p></div></div>; }
function ActionCard({ icon: Icon, title, detail, action, onClick, pending }: { icon: typeof Layers3; title: string; detail: string; action: string; onClick: () => void; pending: boolean }) { return <section className="atlas-surface p-4"><Icon size={18} className="text-[#e8b760]"/><h3 className="mt-4 text-sm font-semibold text-white">{title}</h3><p className="mt-2 text-xs leading-5 text-white/52">{detail}</p><button disabled={pending} onClick={onClick} className="atlas-action mt-4 text-xs disabled:opacity-50">{action}</button></section>; }
function Package({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="rounded-lg border border-white/8 bg-black/20 p-3"><div className="flex justify-between gap-3"><p className="text-xs font-semibold text-white/80">{label}</p><span className="text-[10px] text-[#f0c678]">{value}</span></div><p className="mt-2 text-[11px] leading-5 text-white/47">{detail}</p></div>; }
